# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_v1_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 584)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(9, 9, 75, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 39, 279, 220))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setStyleSheet(_fromUtf8("font: 63 italic 12pt \"Ubuntu\";"))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_14.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setStyleSheet(_fromUtf8("font: 63 italic 12pt \"Ubuntu\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_14.addWidget(self.label_2, QtCore.Qt.AlignRight)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setStyleSheet(_fromUtf8("font: 63 italic 12pt \"Ubuntu\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_14.addWidget(self.label_3, QtCore.Qt.AlignRight)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setStyleSheet(_fromUtf8("font: 63 italic 12pt \"Ubuntu\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_14.addWidget(self.label_4, QtCore.Qt.AlignRight)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setStyleSheet(_fromUtf8("font: 63 italic 12pt \"Ubuntu\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_14.addWidget(self.label_5, QtCore.Qt.AlignRight)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setStyleSheet(_fromUtf8("font: 63 italic 12pt \"Ubuntu\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_14.addWidget(self.label_6, QtCore.Qt.AlignRight)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setStyleSheet(_fromUtf8("font: 63 italic 12pt \"Ubuntu\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_14.addWidget(self.label_7, QtCore.Qt.AlignRight)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setStyleSheet(_fromUtf8("font: 63 italic 12pt \"Ubuntu\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_14.addWidget(self.label_8, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.gridLayout.addLayout(self.verticalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_4.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_4.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_18 = QtGui.QLabel(self.widget)
        self.label_18.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_4.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_4.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(self.widget)
        self.label_20.setStyleSheet(_fromUtf8("font: 63 italic 14pt \"Ubuntu\";"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_4.addWidget(self.label_20)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.groupbox = QtGui.QGroupBox(self.widget)
        self.groupbox.setObjectName(_fromUtf8("groupbox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupbox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_A1 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_A1.setStyleSheet(_fromUtf8("selection-color: rgb(255, 255, 127);"))
        self.radioButton_A1.setText(_fromUtf8(""))
        self.radioButton_A1.setAutoExclusive(False)
        self.radioButton_A1.setObjectName(_fromUtf8("radioButton_A1"))
        self.verticalLayout.addWidget(self.radioButton_A1)
        self.radioButton_B1 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B1.setText(_fromUtf8(""))
        self.radioButton_B1.setAutoExclusive(False)
        self.radioButton_B1.setObjectName(_fromUtf8("radioButton_B1"))
        self.verticalLayout.addWidget(self.radioButton_B1)
        self.radioButton_C1 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C1.setText(_fromUtf8(""))
        self.radioButton_C1.setAutoExclusive(False)
        self.radioButton_C1.setObjectName(_fromUtf8("radioButton_C1"))
        self.verticalLayout.addWidget(self.radioButton_C1)
        self.radioButton_D1 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D1.setText(_fromUtf8(""))
        self.radioButton_D1.setAutoExclusive(False)
        self.radioButton_D1.setObjectName(_fromUtf8("radioButton_D1"))
        self.verticalLayout.addWidget(self.radioButton_D1)
        self.radioButton_E1 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E1.setText(_fromUtf8(""))
        self.radioButton_E1.setAutoExclusive(False)
        self.radioButton_E1.setObjectName(_fromUtf8("radioButton_E1"))
        self.verticalLayout.addWidget(self.radioButton_E1)
        self.radioButton_F1 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F1.setText(_fromUtf8(""))
        self.radioButton_F1.setAutoExclusive(False)
        self.radioButton_F1.setObjectName(_fromUtf8("radioButton_F1"))
        self.verticalLayout.addWidget(self.radioButton_F1)
        self.radioButton_G1 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G1.setText(_fromUtf8(""))
        self.radioButton_G1.setAutoExclusive(False)
        self.radioButton_G1.setObjectName(_fromUtf8("radioButton_G1"))
        self.verticalLayout.addWidget(self.radioButton_G1)
        self.radioButton_H1 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H1.setText(_fromUtf8(""))
        self.radioButton_H1.setAutoExclusive(False)
        self.radioButton_H1.setObjectName(_fromUtf8("radioButton_H1"))
        self.verticalLayout.addWidget(self.radioButton_H1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_A2 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A2.setText(_fromUtf8(""))
        self.radioButton_A2.setAutoExclusive(False)
        self.radioButton_A2.setObjectName(_fromUtf8("radioButton_A2"))
        self.verticalLayout_2.addWidget(self.radioButton_A2)
        self.radioButton_B2 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B2.setText(_fromUtf8(""))
        self.radioButton_B2.setAutoExclusive(False)
        self.radioButton_B2.setObjectName(_fromUtf8("radioButton_B2"))
        self.verticalLayout_2.addWidget(self.radioButton_B2)
        self.radioButton_C2 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C2.setText(_fromUtf8(""))
        self.radioButton_C2.setAutoExclusive(False)
        self.radioButton_C2.setObjectName(_fromUtf8("radioButton_C2"))
        self.verticalLayout_2.addWidget(self.radioButton_C2)
        self.radioButton_D2 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D2.setText(_fromUtf8(""))
        self.radioButton_D2.setAutoExclusive(False)
        self.radioButton_D2.setObjectName(_fromUtf8("radioButton_D2"))
        self.verticalLayout_2.addWidget(self.radioButton_D2)
        self.radioButton_E2 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E2.setText(_fromUtf8(""))
        self.radioButton_E2.setAutoExclusive(False)
        self.radioButton_E2.setObjectName(_fromUtf8("radioButton_E2"))
        self.verticalLayout_2.addWidget(self.radioButton_E2)
        self.radioButton_F2 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F2.setText(_fromUtf8(""))
        self.radioButton_F2.setAutoExclusive(False)
        self.radioButton_F2.setObjectName(_fromUtf8("radioButton_F2"))
        self.verticalLayout_2.addWidget(self.radioButton_F2)
        self.radioButton_G2 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G2.setText(_fromUtf8(""))
        self.radioButton_G2.setAutoExclusive(False)
        self.radioButton_G2.setObjectName(_fromUtf8("radioButton_G2"))
        self.verticalLayout_2.addWidget(self.radioButton_G2)
        self.radioButton_H2 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H2.setText(_fromUtf8(""))
        self.radioButton_H2.setAutoExclusive(False)
        self.radioButton_H2.setObjectName(_fromUtf8("radioButton_H2"))
        self.verticalLayout_2.addWidget(self.radioButton_H2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButton_A3 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A3.setText(_fromUtf8(""))
        self.radioButton_A3.setAutoExclusive(False)
        self.radioButton_A3.setObjectName(_fromUtf8("radioButton_A3"))
        self.verticalLayout_3.addWidget(self.radioButton_A3)
        self.radioButton_B3 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B3.setText(_fromUtf8(""))
        self.radioButton_B3.setAutoExclusive(False)
        self.radioButton_B3.setObjectName(_fromUtf8("radioButton_B3"))
        self.verticalLayout_3.addWidget(self.radioButton_B3)
        self.radioButton_C3 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C3.setText(_fromUtf8(""))
        self.radioButton_C3.setAutoExclusive(False)
        self.radioButton_C3.setObjectName(_fromUtf8("radioButton_C3"))
        self.verticalLayout_3.addWidget(self.radioButton_C3)
        self.radioButton_D3 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D3.setText(_fromUtf8(""))
        self.radioButton_D3.setAutoExclusive(False)
        self.radioButton_D3.setObjectName(_fromUtf8("radioButton_D3"))
        self.verticalLayout_3.addWidget(self.radioButton_D3)
        self.radioButton_E3 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E3.setText(_fromUtf8(""))
        self.radioButton_E3.setAutoExclusive(False)
        self.radioButton_E3.setObjectName(_fromUtf8("radioButton_E3"))
        self.verticalLayout_3.addWidget(self.radioButton_E3)
        self.radioButton_F3 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F3.setText(_fromUtf8(""))
        self.radioButton_F3.setAutoExclusive(False)
        self.radioButton_F3.setObjectName(_fromUtf8("radioButton_F3"))
        self.verticalLayout_3.addWidget(self.radioButton_F3)
        self.radioButton_G3 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G3.setText(_fromUtf8(""))
        self.radioButton_G3.setAutoExclusive(False)
        self.radioButton_G3.setObjectName(_fromUtf8("radioButton_G3"))
        self.verticalLayout_3.addWidget(self.radioButton_G3)
        self.radioButton_H3 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H3.setText(_fromUtf8(""))
        self.radioButton_H3.setAutoExclusive(False)
        self.radioButton_H3.setObjectName(_fromUtf8("radioButton_H3"))
        self.verticalLayout_3.addWidget(self.radioButton_H3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton_A4 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A4.setText(_fromUtf8(""))
        self.radioButton_A4.setAutoExclusive(False)
        self.radioButton_A4.setObjectName(_fromUtf8("radioButton_A4"))
        self.verticalLayout_4.addWidget(self.radioButton_A4)
        self.radioButton_B4 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B4.setText(_fromUtf8(""))
        self.radioButton_B4.setAutoExclusive(False)
        self.radioButton_B4.setObjectName(_fromUtf8("radioButton_B4"))
        self.verticalLayout_4.addWidget(self.radioButton_B4)
        self.radioButton_C4 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C4.setText(_fromUtf8(""))
        self.radioButton_C4.setAutoExclusive(False)
        self.radioButton_C4.setObjectName(_fromUtf8("radioButton_C4"))
        self.verticalLayout_4.addWidget(self.radioButton_C4)
        self.radioButton_D4 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D4.setText(_fromUtf8(""))
        self.radioButton_D4.setAutoExclusive(False)
        self.radioButton_D4.setObjectName(_fromUtf8("radioButton_D4"))
        self.verticalLayout_4.addWidget(self.radioButton_D4)
        self.radioButton_E4 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E4.setText(_fromUtf8(""))
        self.radioButton_E4.setAutoExclusive(False)
        self.radioButton_E4.setObjectName(_fromUtf8("radioButton_E4"))
        self.verticalLayout_4.addWidget(self.radioButton_E4)
        self.radioButton_F4 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F4.setText(_fromUtf8(""))
        self.radioButton_F4.setAutoExclusive(False)
        self.radioButton_F4.setObjectName(_fromUtf8("radioButton_F4"))
        self.verticalLayout_4.addWidget(self.radioButton_F4)
        self.radioButton_G4 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G4.setText(_fromUtf8(""))
        self.radioButton_G4.setAutoExclusive(False)
        self.radioButton_G4.setObjectName(_fromUtf8("radioButton_G4"))
        self.verticalLayout_4.addWidget(self.radioButton_G4)
        self.radioButton_H4 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H4.setText(_fromUtf8(""))
        self.radioButton_H4.setAutoExclusive(False)
        self.radioButton_H4.setObjectName(_fromUtf8("radioButton_H4"))
        self.verticalLayout_4.addWidget(self.radioButton_H4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton_A5 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A5.setText(_fromUtf8(""))
        self.radioButton_A5.setAutoExclusive(False)
        self.radioButton_A5.setObjectName(_fromUtf8("radioButton_A5"))
        self.verticalLayout_5.addWidget(self.radioButton_A5)
        self.radioButton_B5 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B5.setText(_fromUtf8(""))
        self.radioButton_B5.setAutoExclusive(False)
        self.radioButton_B5.setObjectName(_fromUtf8("radioButton_B5"))
        self.verticalLayout_5.addWidget(self.radioButton_B5)
        self.radioButton_C5 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C5.setText(_fromUtf8(""))
        self.radioButton_C5.setAutoExclusive(False)
        self.radioButton_C5.setObjectName(_fromUtf8("radioButton_C5"))
        self.verticalLayout_5.addWidget(self.radioButton_C5)
        self.radioButton_D5 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D5.setText(_fromUtf8(""))
        self.radioButton_D5.setAutoExclusive(False)
        self.radioButton_D5.setObjectName(_fromUtf8("radioButton_D5"))
        self.verticalLayout_5.addWidget(self.radioButton_D5)
        self.radioButton_E5 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E5.setText(_fromUtf8(""))
        self.radioButton_E5.setAutoExclusive(False)
        self.radioButton_E5.setObjectName(_fromUtf8("radioButton_E5"))
        self.verticalLayout_5.addWidget(self.radioButton_E5)
        self.radioButton_F5 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F5.setText(_fromUtf8(""))
        self.radioButton_F5.setAutoExclusive(False)
        self.radioButton_F5.setObjectName(_fromUtf8("radioButton_F5"))
        self.verticalLayout_5.addWidget(self.radioButton_F5)
        self.radioButton_G5 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G5.setText(_fromUtf8(""))
        self.radioButton_G5.setAutoExclusive(False)
        self.radioButton_G5.setObjectName(_fromUtf8("radioButton_G5"))
        self.verticalLayout_5.addWidget(self.radioButton_G5)
        self.radioButton_H5 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H5.setText(_fromUtf8(""))
        self.radioButton_H5.setAutoExclusive(False)
        self.radioButton_H5.setObjectName(_fromUtf8("radioButton_H5"))
        self.verticalLayout_5.addWidget(self.radioButton_H5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.radioButton_A6 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A6.setText(_fromUtf8(""))
        self.radioButton_A6.setAutoExclusive(False)
        self.radioButton_A6.setObjectName(_fromUtf8("radioButton_A6"))
        self.verticalLayout_6.addWidget(self.radioButton_A6)
        self.radioButton_B6 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B6.setText(_fromUtf8(""))
        self.radioButton_B6.setAutoExclusive(False)
        self.radioButton_B6.setObjectName(_fromUtf8("radioButton_B6"))
        self.verticalLayout_6.addWidget(self.radioButton_B6)
        self.radioButton_C6 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C6.setText(_fromUtf8(""))
        self.radioButton_C6.setAutoExclusive(False)
        self.radioButton_C6.setObjectName(_fromUtf8("radioButton_C6"))
        self.verticalLayout_6.addWidget(self.radioButton_C6)
        self.radioButton_D6 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D6.setText(_fromUtf8(""))
        self.radioButton_D6.setAutoExclusive(False)
        self.radioButton_D6.setObjectName(_fromUtf8("radioButton_D6"))
        self.verticalLayout_6.addWidget(self.radioButton_D6)
        self.radioButton_E6 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E6.setText(_fromUtf8(""))
        self.radioButton_E6.setAutoExclusive(False)
        self.radioButton_E6.setObjectName(_fromUtf8("radioButton_E6"))
        self.verticalLayout_6.addWidget(self.radioButton_E6)
        self.radioButton_F6 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F6.setText(_fromUtf8(""))
        self.radioButton_F6.setAutoExclusive(False)
        self.radioButton_F6.setObjectName(_fromUtf8("radioButton_F6"))
        self.verticalLayout_6.addWidget(self.radioButton_F6)
        self.radioButton_G6 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G6.setText(_fromUtf8(""))
        self.radioButton_G6.setAutoExclusive(False)
        self.radioButton_G6.setObjectName(_fromUtf8("radioButton_G6"))
        self.verticalLayout_6.addWidget(self.radioButton_G6)
        self.radioButton_H6 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H6.setText(_fromUtf8(""))
        self.radioButton_H6.setAutoExclusive(False)
        self.radioButton_H6.setObjectName(_fromUtf8("radioButton_H6"))
        self.verticalLayout_6.addWidget(self.radioButton_H6)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.radioButton_A7 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A7.setText(_fromUtf8(""))
        self.radioButton_A7.setAutoExclusive(False)
        self.radioButton_A7.setObjectName(_fromUtf8("radioButton_A7"))
        self.verticalLayout_7.addWidget(self.radioButton_A7)
        self.radioButton_B7 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B7.setText(_fromUtf8(""))
        self.radioButton_B7.setAutoExclusive(False)
        self.radioButton_B7.setObjectName(_fromUtf8("radioButton_B7"))
        self.verticalLayout_7.addWidget(self.radioButton_B7)
        self.radioButton_C7 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C7.setText(_fromUtf8(""))
        self.radioButton_C7.setAutoExclusive(False)
        self.radioButton_C7.setObjectName(_fromUtf8("radioButton_C7"))
        self.verticalLayout_7.addWidget(self.radioButton_C7)
        self.radioButton_D7 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D7.setText(_fromUtf8(""))
        self.radioButton_D7.setAutoExclusive(False)
        self.radioButton_D7.setObjectName(_fromUtf8("radioButton_D7"))
        self.verticalLayout_7.addWidget(self.radioButton_D7)
        self.radioButton_E7 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E7.setText(_fromUtf8(""))
        self.radioButton_E7.setAutoExclusive(False)
        self.radioButton_E7.setObjectName(_fromUtf8("radioButton_E7"))
        self.verticalLayout_7.addWidget(self.radioButton_E7)
        self.radioButton_F7 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F7.setText(_fromUtf8(""))
        self.radioButton_F7.setAutoExclusive(False)
        self.radioButton_F7.setObjectName(_fromUtf8("radioButton_F7"))
        self.verticalLayout_7.addWidget(self.radioButton_F7)
        self.radioButton_G7 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G7.setText(_fromUtf8(""))
        self.radioButton_G7.setAutoExclusive(False)
        self.radioButton_G7.setObjectName(_fromUtf8("radioButton_G7"))
        self.verticalLayout_7.addWidget(self.radioButton_G7)
        self.radioButton_H7 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H7.setText(_fromUtf8(""))
        self.radioButton_H7.setAutoExclusive(False)
        self.radioButton_H7.setObjectName(_fromUtf8("radioButton_H7"))
        self.verticalLayout_7.addWidget(self.radioButton_H7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.radioButton_A8 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A8.setText(_fromUtf8(""))
        self.radioButton_A8.setAutoExclusive(False)
        self.radioButton_A8.setObjectName(_fromUtf8("radioButton_A8"))
        self.verticalLayout_17.addWidget(self.radioButton_A8)
        self.radioButton_B8 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B8.setText(_fromUtf8(""))
        self.radioButton_B8.setAutoExclusive(False)
        self.radioButton_B8.setObjectName(_fromUtf8("radioButton_B8"))
        self.verticalLayout_17.addWidget(self.radioButton_B8)
        self.radioButton_C8 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C8.setText(_fromUtf8(""))
        self.radioButton_C8.setAutoExclusive(False)
        self.radioButton_C8.setObjectName(_fromUtf8("radioButton_C8"))
        self.verticalLayout_17.addWidget(self.radioButton_C8)
        self.radioButton_D8 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D8.setText(_fromUtf8(""))
        self.radioButton_D8.setAutoExclusive(False)
        self.radioButton_D8.setObjectName(_fromUtf8("radioButton_D8"))
        self.verticalLayout_17.addWidget(self.radioButton_D8)
        self.radioButton_E8 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E8.setText(_fromUtf8(""))
        self.radioButton_E8.setAutoExclusive(False)
        self.radioButton_E8.setObjectName(_fromUtf8("radioButton_E8"))
        self.verticalLayout_17.addWidget(self.radioButton_E8)
        self.radioButton_F8 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F8.setText(_fromUtf8(""))
        self.radioButton_F8.setAutoExclusive(False)
        self.radioButton_F8.setObjectName(_fromUtf8("radioButton_F8"))
        self.verticalLayout_17.addWidget(self.radioButton_F8)
        self.radioButton_G8 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G8.setText(_fromUtf8(""))
        self.radioButton_G8.setAutoExclusive(False)
        self.radioButton_G8.setObjectName(_fromUtf8("radioButton_G8"))
        self.verticalLayout_17.addWidget(self.radioButton_G8)
        self.radioButton_H8 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H8.setText(_fromUtf8(""))
        self.radioButton_H8.setAutoExclusive(False)
        self.radioButton_H8.setObjectName(_fromUtf8("radioButton_H8"))
        self.verticalLayout_17.addWidget(self.radioButton_H8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.radioButton_A9 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A9.setText(_fromUtf8(""))
        self.radioButton_A9.setAutoExclusive(False)
        self.radioButton_A9.setObjectName(_fromUtf8("radioButton_A9"))
        self.verticalLayout_18.addWidget(self.radioButton_A9)
        self.radioButton_B9 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B9.setText(_fromUtf8(""))
        self.radioButton_B9.setAutoExclusive(False)
        self.radioButton_B9.setObjectName(_fromUtf8("radioButton_B9"))
        self.verticalLayout_18.addWidget(self.radioButton_B9)
        self.radioButton_C9 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C9.setText(_fromUtf8(""))
        self.radioButton_C9.setAutoExclusive(False)
        self.radioButton_C9.setObjectName(_fromUtf8("radioButton_C9"))
        self.verticalLayout_18.addWidget(self.radioButton_C9)
        self.radioButton_D9 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D9.setText(_fromUtf8(""))
        self.radioButton_D9.setAutoExclusive(False)
        self.radioButton_D9.setObjectName(_fromUtf8("radioButton_D9"))
        self.verticalLayout_18.addWidget(self.radioButton_D9)
        self.radioButton_E9 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E9.setText(_fromUtf8(""))
        self.radioButton_E9.setAutoExclusive(False)
        self.radioButton_E9.setObjectName(_fromUtf8("radioButton_E9"))
        self.verticalLayout_18.addWidget(self.radioButton_E9)
        self.radioButton_F9 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F9.setText(_fromUtf8(""))
        self.radioButton_F9.setAutoExclusive(False)
        self.radioButton_F9.setObjectName(_fromUtf8("radioButton_F9"))
        self.verticalLayout_18.addWidget(self.radioButton_F9)
        self.radioButton_G9 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G9.setText(_fromUtf8(""))
        self.radioButton_G9.setAutoExclusive(False)
        self.radioButton_G9.setObjectName(_fromUtf8("radioButton_G9"))
        self.verticalLayout_18.addWidget(self.radioButton_G9)
        self.radioButton_H9 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H9.setText(_fromUtf8(""))
        self.radioButton_H9.setAutoExclusive(False)
        self.radioButton_H9.setObjectName(_fromUtf8("radioButton_H9"))
        self.verticalLayout_18.addWidget(self.radioButton_H9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.radioButton_A10 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A10.setText(_fromUtf8(""))
        self.radioButton_A10.setAutoExclusive(False)
        self.radioButton_A10.setObjectName(_fromUtf8("radioButton_A10"))
        self.verticalLayout_19.addWidget(self.radioButton_A10)
        self.radioButton_B10 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B10.setText(_fromUtf8(""))
        self.radioButton_B10.setAutoExclusive(False)
        self.radioButton_B10.setObjectName(_fromUtf8("radioButton_B10"))
        self.verticalLayout_19.addWidget(self.radioButton_B10)
        self.radioButton_C10 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C10.setText(_fromUtf8(""))
        self.radioButton_C10.setAutoExclusive(False)
        self.radioButton_C10.setObjectName(_fromUtf8("radioButton_C10"))
        self.verticalLayout_19.addWidget(self.radioButton_C10)
        self.radioButton_D10 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D10.setText(_fromUtf8(""))
        self.radioButton_D10.setAutoExclusive(False)
        self.radioButton_D10.setObjectName(_fromUtf8("radioButton_D10"))
        self.verticalLayout_19.addWidget(self.radioButton_D10)
        self.radioButton_E10 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E10.setText(_fromUtf8(""))
        self.radioButton_E10.setAutoExclusive(False)
        self.radioButton_E10.setObjectName(_fromUtf8("radioButton_E10"))
        self.verticalLayout_19.addWidget(self.radioButton_E10)
        self.radioButton_F10 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F10.setText(_fromUtf8(""))
        self.radioButton_F10.setAutoExclusive(False)
        self.radioButton_F10.setObjectName(_fromUtf8("radioButton_F10"))
        self.verticalLayout_19.addWidget(self.radioButton_F10)
        self.radioButton_G10 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G10.setText(_fromUtf8(""))
        self.radioButton_G10.setAutoExclusive(False)
        self.radioButton_G10.setObjectName(_fromUtf8("radioButton_G10"))
        self.verticalLayout_19.addWidget(self.radioButton_G10)
        self.radioButton_H10 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H10.setText(_fromUtf8(""))
        self.radioButton_H10.setAutoExclusive(False)
        self.radioButton_H10.setObjectName(_fromUtf8("radioButton_H10"))
        self.verticalLayout_19.addWidget(self.radioButton_H10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.radioButton_A11 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A11.setText(_fromUtf8(""))
        self.radioButton_A11.setAutoExclusive(False)
        self.radioButton_A11.setObjectName(_fromUtf8("radioButton_A11"))
        self.verticalLayout_20.addWidget(self.radioButton_A11)
        self.radioButton_B11 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B11.setText(_fromUtf8(""))
        self.radioButton_B11.setAutoExclusive(False)
        self.radioButton_B11.setObjectName(_fromUtf8("radioButton_B11"))
        self.verticalLayout_20.addWidget(self.radioButton_B11)
        self.radioButton_C11 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C11.setText(_fromUtf8(""))
        self.radioButton_C11.setAutoExclusive(False)
        self.radioButton_C11.setObjectName(_fromUtf8("radioButton_C11"))
        self.verticalLayout_20.addWidget(self.radioButton_C11)
        self.radioButton_D11 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D11.setText(_fromUtf8(""))
        self.radioButton_D11.setAutoExclusive(False)
        self.radioButton_D11.setObjectName(_fromUtf8("radioButton_D11"))
        self.verticalLayout_20.addWidget(self.radioButton_D11)
        self.radioButton_E11 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E11.setText(_fromUtf8(""))
        self.radioButton_E11.setAutoExclusive(False)
        self.radioButton_E11.setObjectName(_fromUtf8("radioButton_E11"))
        self.verticalLayout_20.addWidget(self.radioButton_E11)
        self.radioButton_F11 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F11.setText(_fromUtf8(""))
        self.radioButton_F11.setAutoExclusive(False)
        self.radioButton_F11.setObjectName(_fromUtf8("radioButton_F11"))
        self.verticalLayout_20.addWidget(self.radioButton_F11)
        self.radioButton_G11 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G11.setText(_fromUtf8(""))
        self.radioButton_G11.setAutoExclusive(False)
        self.radioButton_G11.setObjectName(_fromUtf8("radioButton_G11"))
        self.verticalLayout_20.addWidget(self.radioButton_G11)
        self.radioButton_H11 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H11.setText(_fromUtf8(""))
        self.radioButton_H11.setAutoExclusive(False)
        self.radioButton_H11.setObjectName(_fromUtf8("radioButton_H11"))
        self.verticalLayout_20.addWidget(self.radioButton_H11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.radioButton_A12 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_A12.setText(_fromUtf8(""))
        self.radioButton_A12.setAutoExclusive(False)
        self.radioButton_A12.setObjectName(_fromUtf8("radioButton_A12"))
        self.verticalLayout_21.addWidget(self.radioButton_A12)
        self.radioButton_B12 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_B12.setText(_fromUtf8(""))
        self.radioButton_B12.setAutoExclusive(False)
        self.radioButton_B12.setObjectName(_fromUtf8("radioButton_B12"))
        self.verticalLayout_21.addWidget(self.radioButton_B12)
        self.radioButton_C12 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_C12.setText(_fromUtf8(""))
        self.radioButton_C12.setAutoExclusive(False)
        self.radioButton_C12.setObjectName(_fromUtf8("radioButton_C12"))
        self.verticalLayout_21.addWidget(self.radioButton_C12)
        self.radioButton_D12 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_D12.setText(_fromUtf8(""))
        self.radioButton_D12.setAutoExclusive(False)
        self.radioButton_D12.setObjectName(_fromUtf8("radioButton_D12"))
        self.verticalLayout_21.addWidget(self.radioButton_D12)
        self.radioButton_E12 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_E12.setText(_fromUtf8(""))
        self.radioButton_E12.setAutoExclusive(False)
        self.radioButton_E12.setObjectName(_fromUtf8("radioButton_E12"))
        self.verticalLayout_21.addWidget(self.radioButton_E12)
        self.radioButton_F12 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_F12.setText(_fromUtf8(""))
        self.radioButton_F12.setAutoExclusive(False)
        self.radioButton_F12.setObjectName(_fromUtf8("radioButton_F12"))
        self.verticalLayout_21.addWidget(self.radioButton_F12)
        self.radioButton_G12 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_G12.setText(_fromUtf8(""))
        self.radioButton_G12.setAutoExclusive(False)
        self.radioButton_G12.setObjectName(_fromUtf8("radioButton_G12"))
        self.verticalLayout_21.addWidget(self.radioButton_G12)
        self.radioButton_H12 = QtGui.QRadioButton(self.groupbox)
        self.radioButton_H12.setText(_fromUtf8(""))
        self.radioButton_H12.setAutoExclusive(False)
        self.radioButton_H12.setObjectName(_fromUtf8("radioButton_H12"))
        self.verticalLayout_21.addWidget(self.radioButton_H12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_21)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupbox, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "Start", None))
        self.label.setText(_translate("MainWindow", "A", None))
        self.label_2.setText(_translate("MainWindow", "B", None))
        self.label_3.setText(_translate("MainWindow", "C", None))
        self.label_4.setText(_translate("MainWindow", "D", None))
        self.label_5.setText(_translate("MainWindow", "E", None))
        self.label_6.setText(_translate("MainWindow", "F", None))
        self.label_7.setText(_translate("MainWindow", "G", None))
        self.label_8.setText(_translate("MainWindow", "H", None))
        self.label_9.setText(_translate("MainWindow", "1", None))
        self.label_10.setText(_translate("MainWindow", "2", None))
        self.label_11.setText(_translate("MainWindow", "3", None))
        self.label_12.setText(_translate("MainWindow", "4", None))
        self.label_13.setText(_translate("MainWindow", "5", None))
        self.label_14.setText(_translate("MainWindow", "6", None))
        self.label_15.setText(_translate("MainWindow", "7", None))
        self.label_16.setText(_translate("MainWindow", "8", None))
        self.label_17.setText(_translate("MainWindow", "9", None))
        self.label_18.setText(_translate("MainWindow", "10", None))
        self.label_19.setText(_translate("MainWindow", "11", None))
        self.label_20.setText(_translate("MainWindow", "12", None))

