# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'replacement_well_menu.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class wellplateMenu(QtGui.QWidget):
    def __init__(self):
        super(wellplateMenu, self).__init__()
        self.initUI()

    def initUI(self):
        self.setObjectName(_fromUtf8("Well Plate Menu"))
        self.resize(788, 306)
        self.absButton = QtGui.QPushButton(self)
        self.absButton.setGeometry(QtCore.QRect(10, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.absButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Python_GUI/absorbanceLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.absButton.setIcon(icon)
        self.absButton.setIconSize(QtCore.QSize(25, 25))
        self.absButton.setObjectName(_fromUtf8("absButton"))
        self.absSpecButton = QtGui.QPushButton(self)
        self.absSpecButton.setGeometry(QtCore.QRect(140, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.absSpecButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../Python_GUI/absSpectrumLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.absSpecButton.setIcon(icon1)
        self.absSpecButton.setIconSize(QtCore.QSize(25, 25))
        self.absSpecButton.setObjectName(_fromUtf8("absSpecButton"))
        self.flrButton = QtGui.QPushButton(self)
        self.flrButton.setGeometry(QtCore.QRect(270, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.flrButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../Python_GUI/flourescenceLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flrButton.setIcon(icon2)
        self.flrButton.setIconSize(QtCore.QSize(25, 25))
        self.flrButton.setObjectName(_fromUtf8("flrButton"))
        self.flrSpecButton = QtGui.QPushButton(self)
        self.flrSpecButton.setGeometry(QtCore.QRect(400, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.flrSpecButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../Python_GUI/flrSpectrumLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flrSpecButton.setIcon(icon3)
        self.flrSpecButton.setIconSize(QtCore.QSize(25, 25))
        self.flrSpecButton.setObjectName(_fromUtf8("flrSpecButton"))
        self.shakeButton = QtGui.QPushButton(self)
        self.shakeButton.setGeometry(QtCore.QRect(530, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shakeButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../Python_GUI/shakeLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shakeButton.setIcon(icon4)
        self.shakeButton.setIconSize(QtCore.QSize(40, 40))
        self.shakeButton.setObjectName(_fromUtf8("shakeButton"))
        self.kineticsButton = QtGui.QPushButton(self)
        self.kineticsButton.setGeometry(QtCore.QRect(660, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kineticsButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../Python_GUI/886e08dc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kineticsButton.setIcon(icon5)
        self.kineticsButton.setIconSize(QtCore.QSize(25, 25))
        self.kineticsButton.setObjectName(_fromUtf8("kineticsButton"))
        self.line = QtGui.QFrame(self)
        self.line.setGeometry(QtCore.QRect(10, 230, 771, 16))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.protocolLabel = QtGui.QLineEdit(self)
        self.protocolLabel.setGeometry(QtCore.QRect(400, 90, 241, 21))
        self.protocolLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.protocolLabel.setObjectName(_fromUtf8("protocolLabel"))
        self.clearWellsButton = QtGui.QPushButton(self)
        self.clearWellsButton.setGeometry(QtCore.QRect(400, 130, 241, 31))
        self.clearWellsButton.setObjectName(_fromUtf8("clearWellsButton"))
        self.deletePlateButton = QtGui.QPushButton(self)
        self.deletePlateButton.setGeometry(QtCore.QRect(400, 180, 241, 31))
        self.deletePlateButton.setObjectName(_fromUtf8("deletePlateButton"))
        self.closeButton = QtGui.QPushButton(self)
        self.closeButton.setGeometry(QtCore.QRect(760, 10, 21, 21))
        self.closeButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../Python_GUI/x-mark-4-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon6)
        self.closeButton.setIconSize(QtCore.QSize(12, 12))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.layoutWidget = QtGui.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 11, 351, 221))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 5, 1, 1)
        self.B5 = QtGui.QRadioButton(self.layoutWidget)
        self.B5.setText(_fromUtf8(""))
        self.B5.setAutoExclusive(False)
        self.B5.setObjectName(_fromUtf8("B5"))
        self.gridLayout.addWidget(self.B5, 2, 5, 1, 1)
        self.A1 = QtGui.QRadioButton(self.layoutWidget)
        self.A1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.A1.setText(_fromUtf8(""))
        self.A1.setAutoExclusive(False)
        self.A1.setObjectName(_fromUtf8("A1"))
        self.gridLayout.addWidget(self.A1, 1, 1, 1, 1)
        self.B9 = QtGui.QRadioButton(self.layoutWidget)
        self.B9.setText(_fromUtf8(""))
        self.B9.setAutoExclusive(False)
        self.B9.setObjectName(_fromUtf8("B9"))
        self.gridLayout.addWidget(self.B9, 2, 9, 1, 1)
        self.B2 = QtGui.QRadioButton(self.layoutWidget)
        self.B2.setText(_fromUtf8(""))
        self.B2.setAutoExclusive(False)
        self.B2.setObjectName(_fromUtf8("B2"))
        self.gridLayout.addWidget(self.B2, 2, 2, 1, 1)
        self.A9 = QtGui.QRadioButton(self.layoutWidget)
        self.A9.setText(_fromUtf8(""))
        self.A9.setAutoExclusive(False)
        self.A9.setObjectName(_fromUtf8("A9"))
        self.gridLayout.addWidget(self.A9, 1, 9, 1, 1)
        self.B4 = QtGui.QRadioButton(self.layoutWidget)
        self.B4.setText(_fromUtf8(""))
        self.B4.setAutoExclusive(False)
        self.B4.setObjectName(_fromUtf8("B4"))
        self.gridLayout.addWidget(self.B4, 2, 4, 1, 1)
        self.A2 = QtGui.QRadioButton(self.layoutWidget)
        self.A2.setText(_fromUtf8(""))
        self.A2.setAutoExclusive(False)
        self.A2.setObjectName(_fromUtf8("A2"))
        self.gridLayout.addWidget(self.A2, 1, 2, 1, 1)
        self.B7 = QtGui.QRadioButton(self.layoutWidget)
        self.B7.setText(_fromUtf8(""))
        self.B7.setAutoExclusive(False)
        self.B7.setObjectName(_fromUtf8("B7"))
        self.gridLayout.addWidget(self.B7, 2, 7, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 7, 1, 1)
        self.B10 = QtGui.QRadioButton(self.layoutWidget)
        self.B10.setText(_fromUtf8(""))
        self.B10.setAutoExclusive(False)
        self.B10.setObjectName(_fromUtf8("B10"))
        self.gridLayout.addWidget(self.B10, 2, 10, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 0, 12, 1, 1)
        self.B1 = QtGui.QRadioButton(self.layoutWidget)
        self.B1.setText(_fromUtf8(""))
        self.B1.setAutoExclusive(False)
        self.B1.setObjectName(_fromUtf8("B1"))
        self.gridLayout.addWidget(self.B1, 2, 1, 1, 1)
        self.B11 = QtGui.QRadioButton(self.layoutWidget)
        self.B11.setText(_fromUtf8(""))
        self.B11.setAutoExclusive(False)
        self.B11.setObjectName(_fromUtf8("B11"))
        self.gridLayout.addWidget(self.B11, 2, 11, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 10, 1, 1)
        self.A7 = QtGui.QRadioButton(self.layoutWidget)
        self.A7.setText(_fromUtf8(""))
        self.A7.setAutoExclusive(False)
        self.A7.setObjectName(_fromUtf8("A7"))
        self.gridLayout.addWidget(self.A7, 1, 7, 1, 1)
        self.A8 = QtGui.QRadioButton(self.layoutWidget)
        self.A8.setText(_fromUtf8(""))
        self.A8.setAutoExclusive(False)
        self.A8.setObjectName(_fromUtf8("A8"))
        self.gridLayout.addWidget(self.A8, 1, 8, 1, 1)
        self.B6 = QtGui.QRadioButton(self.layoutWidget)
        self.B6.setText(_fromUtf8(""))
        self.B6.setAutoExclusive(False)
        self.B6.setObjectName(_fromUtf8("B6"))
        self.gridLayout.addWidget(self.B6, 2, 6, 1, 1)
        self.B3 = QtGui.QRadioButton(self.layoutWidget)
        self.B3.setText(_fromUtf8(""))
        self.B3.setAutoExclusive(False)
        self.B3.setObjectName(_fromUtf8("B3"))
        self.gridLayout.addWidget(self.B3, 2, 3, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.A4 = QtGui.QRadioButton(self.layoutWidget)
        self.A4.setText(_fromUtf8(""))
        self.A4.setAutoExclusive(False)
        self.A4.setObjectName(_fromUtf8("A4"))
        self.gridLayout.addWidget(self.A4, 1, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 6, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 0, 11, 1, 1)
        self.A3 = QtGui.QRadioButton(self.layoutWidget)
        self.A3.setText(_fromUtf8(""))
        self.A3.setAutoExclusive(False)
        self.A3.setObjectName(_fromUtf8("A3"))
        self.gridLayout.addWidget(self.A3, 1, 3, 1, 1)
        self.A5 = QtGui.QRadioButton(self.layoutWidget)
        self.A5.setText(_fromUtf8(""))
        self.A5.setAutoExclusive(False)
        self.A5.setObjectName(_fromUtf8("A5"))
        self.gridLayout.addWidget(self.A5, 1, 5, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 0, 8, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 0, 9, 1, 1)
        self.A6 = QtGui.QRadioButton(self.layoutWidget)
        self.A6.setText(_fromUtf8(""))
        self.A6.setAutoExclusive(False)
        self.A6.setObjectName(_fromUtf8("A6"))
        self.gridLayout.addWidget(self.A6, 1, 6, 1, 1)
        self.A10 = QtGui.QRadioButton(self.layoutWidget)
        self.A10.setText(_fromUtf8(""))
        self.A10.setAutoExclusive(False)
        self.A10.setObjectName(_fromUtf8("A10"))
        self.gridLayout.addWidget(self.A10, 1, 10, 1, 1)
        self.A11 = QtGui.QRadioButton(self.layoutWidget)
        self.A11.setText(_fromUtf8(""))
        self.A11.setAutoExclusive(False)
        self.A11.setObjectName(_fromUtf8("A11"))
        self.gridLayout.addWidget(self.A11, 1, 11, 1, 1)
        self.A12 = QtGui.QRadioButton(self.layoutWidget)
        self.A12.setText(_fromUtf8(""))
        self.A12.setAutoExclusive(False)
        self.A12.setObjectName(_fromUtf8("A12"))
        self.gridLayout.addWidget(self.A12, 1, 12, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.B8 = QtGui.QRadioButton(self.layoutWidget)
        self.B8.setText(_fromUtf8(""))
        self.B8.setAutoExclusive(False)
        self.B8.setObjectName(_fromUtf8("B8"))
        self.gridLayout.addWidget(self.B8, 2, 8, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.E2 = QtGui.QRadioButton(self.layoutWidget)
        self.E2.setText(_fromUtf8(""))
        self.E2.setAutoExclusive(False)
        self.E2.setObjectName(_fromUtf8("E2"))
        self.gridLayout.addWidget(self.E2, 5, 2, 1, 1)
        self.C10 = QtGui.QRadioButton(self.layoutWidget)
        self.C10.setText(_fromUtf8(""))
        self.C10.setAutoExclusive(False)
        self.C10.setObjectName(_fromUtf8("C10"))
        self.gridLayout.addWidget(self.C10, 3, 10, 1, 1)
        self.D11 = QtGui.QRadioButton(self.layoutWidget)
        self.D11.setText(_fromUtf8(""))
        self.D11.setAutoExclusive(False)
        self.D11.setObjectName(_fromUtf8("D11"))
        self.gridLayout.addWidget(self.D11, 4, 11, 1, 1)
        self.C5 = QtGui.QRadioButton(self.layoutWidget)
        self.C5.setText(_fromUtf8(""))
        self.C5.setAutoExclusive(False)
        self.C5.setObjectName(_fromUtf8("C5"))
        self.gridLayout.addWidget(self.C5, 3, 5, 1, 1)
        self.D5 = QtGui.QRadioButton(self.layoutWidget)
        self.D5.setText(_fromUtf8(""))
        self.D5.setAutoExclusive(False)
        self.D5.setObjectName(_fromUtf8("D5"))
        self.gridLayout.addWidget(self.D5, 4, 5, 1, 1)
        self.E1 = QtGui.QRadioButton(self.layoutWidget)
        self.E1.setText(_fromUtf8(""))
        self.E1.setAutoExclusive(False)
        self.E1.setObjectName(_fromUtf8("E1"))
        self.gridLayout.addWidget(self.E1, 5, 1, 1, 1)
        self.C1 = QtGui.QRadioButton(self.layoutWidget)
        self.C1.setText(_fromUtf8(""))
        self.C1.setAutoExclusive(False)
        self.C1.setObjectName(_fromUtf8("C1"))
        self.gridLayout.addWidget(self.C1, 3, 1, 1, 1)
        self.E3 = QtGui.QRadioButton(self.layoutWidget)
        self.E3.setText(_fromUtf8(""))
        self.E3.setAutoExclusive(False)
        self.E3.setObjectName(_fromUtf8("E3"))
        self.gridLayout.addWidget(self.E3, 5, 3, 1, 1)
        self.E4 = QtGui.QRadioButton(self.layoutWidget)
        self.E4.setText(_fromUtf8(""))
        self.E4.setAutoExclusive(False)
        self.E4.setObjectName(_fromUtf8("E4"))
        self.gridLayout.addWidget(self.E4, 5, 4, 1, 1)
        self.C12 = QtGui.QRadioButton(self.layoutWidget)
        self.C12.setText(_fromUtf8(""))
        self.C12.setAutoExclusive(False)
        self.C12.setObjectName(_fromUtf8("C12"))
        self.gridLayout.addWidget(self.C12, 3, 12, 1, 1)
        self.C4 = QtGui.QRadioButton(self.layoutWidget)
        self.C4.setText(_fromUtf8(""))
        self.C4.setAutoExclusive(False)
        self.C4.setObjectName(_fromUtf8("C4"))
        self.gridLayout.addWidget(self.C4, 3, 4, 1, 1)
        self.C3 = QtGui.QRadioButton(self.layoutWidget)
        self.C3.setText(_fromUtf8(""))
        self.C3.setAutoExclusive(False)
        self.C3.setObjectName(_fromUtf8("C3"))
        self.gridLayout.addWidget(self.C3, 3, 3, 1, 1)
        self.D3 = QtGui.QRadioButton(self.layoutWidget)
        self.D3.setText(_fromUtf8(""))
        self.D3.setAutoExclusive(False)
        self.D3.setObjectName(_fromUtf8("D3"))
        self.gridLayout.addWidget(self.D3, 4, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.C9 = QtGui.QRadioButton(self.layoutWidget)
        self.C9.setText(_fromUtf8(""))
        self.C9.setAutoExclusive(False)
        self.C9.setObjectName(_fromUtf8("C9"))
        self.gridLayout.addWidget(self.C9, 3, 9, 1, 1)
        self.C6 = QtGui.QRadioButton(self.layoutWidget)
        self.C6.setText(_fromUtf8(""))
        self.C6.setAutoExclusive(False)
        self.C6.setObjectName(_fromUtf8("C6"))
        self.gridLayout.addWidget(self.C6, 3, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.D1 = QtGui.QRadioButton(self.layoutWidget)
        self.D1.setText(_fromUtf8(""))
        self.D1.setAutoExclusive(False)
        self.D1.setObjectName(_fromUtf8("D1"))
        self.gridLayout.addWidget(self.D1, 4, 1, 1, 1)
        self.C11 = QtGui.QRadioButton(self.layoutWidget)
        self.C11.setText(_fromUtf8(""))
        self.C11.setAutoExclusive(False)
        self.C11.setObjectName(_fromUtf8("C11"))
        self.gridLayout.addWidget(self.C11, 3, 11, 1, 1)
        self.C2 = QtGui.QRadioButton(self.layoutWidget)
        self.C2.setText(_fromUtf8(""))
        self.C2.setAutoExclusive(False)
        self.C2.setObjectName(_fromUtf8("C2"))
        self.gridLayout.addWidget(self.C2, 3, 2, 1, 1)
        self.C8 = QtGui.QRadioButton(self.layoutWidget)
        self.C8.setText(_fromUtf8(""))
        self.C8.setAutoExclusive(False)
        self.C8.setObjectName(_fromUtf8("C8"))
        self.gridLayout.addWidget(self.C8, 3, 8, 1, 1)
        self.D2 = QtGui.QRadioButton(self.layoutWidget)
        self.D2.setText(_fromUtf8(""))
        self.D2.setAutoExclusive(False)
        self.D2.setObjectName(_fromUtf8("D2"))
        self.gridLayout.addWidget(self.D2, 4, 2, 1, 1)
        self.D4 = QtGui.QRadioButton(self.layoutWidget)
        self.D4.setText(_fromUtf8(""))
        self.D4.setAutoExclusive(False)
        self.D4.setObjectName(_fromUtf8("D4"))
        self.gridLayout.addWidget(self.D4, 4, 4, 1, 1)
        self.D6 = QtGui.QRadioButton(self.layoutWidget)
        self.D6.setText(_fromUtf8(""))
        self.D6.setAutoExclusive(False)
        self.D6.setObjectName(_fromUtf8("D6"))
        self.gridLayout.addWidget(self.D6, 4, 6, 1, 1)
        self.D7 = QtGui.QRadioButton(self.layoutWidget)
        self.D7.setText(_fromUtf8(""))
        self.D7.setAutoExclusive(False)
        self.D7.setObjectName(_fromUtf8("D7"))
        self.gridLayout.addWidget(self.D7, 4, 7, 1, 1)
        self.D8 = QtGui.QRadioButton(self.layoutWidget)
        self.D8.setText(_fromUtf8(""))
        self.D8.setAutoExclusive(False)
        self.D8.setObjectName(_fromUtf8("D8"))
        self.gridLayout.addWidget(self.D8, 4, 8, 1, 1)
        self.D9 = QtGui.QRadioButton(self.layoutWidget)
        self.D9.setText(_fromUtf8(""))
        self.D9.setAutoExclusive(False)
        self.D9.setObjectName(_fromUtf8("D9"))
        self.gridLayout.addWidget(self.D9, 4, 9, 1, 1)
        self.B12 = QtGui.QRadioButton(self.layoutWidget)
        self.B12.setText(_fromUtf8(""))
        self.B12.setAutoExclusive(False)
        self.B12.setObjectName(_fromUtf8("B12"))
        self.gridLayout.addWidget(self.B12, 2, 12, 1, 1)
        self.D10 = QtGui.QRadioButton(self.layoutWidget)
        self.D10.setText(_fromUtf8(""))
        self.D10.setAutoExclusive(False)
        self.D10.setObjectName(_fromUtf8("D10"))
        self.gridLayout.addWidget(self.D10, 4, 10, 1, 1)
        self.C7 = QtGui.QRadioButton(self.layoutWidget)
        self.C7.setText(_fromUtf8(""))
        self.C7.setAutoExclusive(False)
        self.C7.setObjectName(_fromUtf8("C7"))
        self.gridLayout.addWidget(self.C7, 3, 7, 1, 1)
        self.D12 = QtGui.QRadioButton(self.layoutWidget)
        self.D12.setText(_fromUtf8(""))
        self.D12.setAutoExclusive(False)
        self.D12.setObjectName(_fromUtf8("D12"))
        self.gridLayout.addWidget(self.D12, 4, 12, 1, 1)
        self.G4 = QtGui.QRadioButton(self.layoutWidget)
        self.G4.setText(_fromUtf8(""))
        self.G4.setAutoExclusive(False)
        self.G4.setObjectName(_fromUtf8("G4"))
        self.gridLayout.addWidget(self.G4, 7, 4, 1, 1)
        self.E10 = QtGui.QRadioButton(self.layoutWidget)
        self.E10.setText(_fromUtf8(""))
        self.E10.setAutoExclusive(False)
        self.E10.setObjectName(_fromUtf8("E10"))
        self.gridLayout.addWidget(self.E10, 5, 10, 1, 1)
        self.E5 = QtGui.QRadioButton(self.layoutWidget)
        self.E5.setText(_fromUtf8(""))
        self.E5.setAutoExclusive(False)
        self.E5.setObjectName(_fromUtf8("E5"))
        self.gridLayout.addWidget(self.E5, 5, 5, 1, 1)
        self.E6 = QtGui.QRadioButton(self.layoutWidget)
        self.E6.setText(_fromUtf8(""))
        self.E6.setAutoExclusive(False)
        self.E6.setObjectName(_fromUtf8("E6"))
        self.gridLayout.addWidget(self.E6, 5, 6, 1, 1)
        self.E12 = QtGui.QRadioButton(self.layoutWidget)
        self.E12.setText(_fromUtf8(""))
        self.E12.setAutoExclusive(False)
        self.E12.setObjectName(_fromUtf8("E12"))
        self.gridLayout.addWidget(self.E12, 5, 12, 1, 1)
        self.F8 = QtGui.QRadioButton(self.layoutWidget)
        self.F8.setText(_fromUtf8(""))
        self.F8.setAutoExclusive(False)
        self.F8.setObjectName(_fromUtf8("F8"))
        self.gridLayout.addWidget(self.F8, 6, 8, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.E11 = QtGui.QRadioButton(self.layoutWidget)
        self.E11.setText(_fromUtf8(""))
        self.E11.setAutoExclusive(False)
        self.E11.setObjectName(_fromUtf8("E11"))
        self.gridLayout.addWidget(self.E11, 5, 11, 1, 1)
        self.G5 = QtGui.QRadioButton(self.layoutWidget)
        self.G5.setText(_fromUtf8(""))
        self.G5.setAutoExclusive(False)
        self.G5.setObjectName(_fromUtf8("G5"))
        self.gridLayout.addWidget(self.G5, 7, 5, 1, 1)
        self.G8 = QtGui.QRadioButton(self.layoutWidget)
        self.G8.setText(_fromUtf8(""))
        self.G8.setAutoExclusive(False)
        self.G8.setObjectName(_fromUtf8("G8"))
        self.gridLayout.addWidget(self.G8, 7, 8, 1, 1)
        self.F2 = QtGui.QRadioButton(self.layoutWidget)
        self.F2.setText(_fromUtf8(""))
        self.F2.setAutoExclusive(False)
        self.F2.setObjectName(_fromUtf8("F2"))
        self.gridLayout.addWidget(self.F2, 6, 2, 1, 1)
        self.G9 = QtGui.QRadioButton(self.layoutWidget)
        self.G9.setText(_fromUtf8(""))
        self.G9.setAutoExclusive(False)
        self.G9.setObjectName(_fromUtf8("G9"))
        self.gridLayout.addWidget(self.G9, 7, 9, 1, 1)
        self.E8 = QtGui.QRadioButton(self.layoutWidget)
        self.E8.setText(_fromUtf8(""))
        self.E8.setAutoExclusive(False)
        self.E8.setObjectName(_fromUtf8("E8"))
        self.gridLayout.addWidget(self.E8, 5, 8, 1, 1)
        self.F9 = QtGui.QRadioButton(self.layoutWidget)
        self.F9.setText(_fromUtf8(""))
        self.F9.setAutoExclusive(False)
        self.F9.setObjectName(_fromUtf8("F9"))
        self.gridLayout.addWidget(self.F9, 6, 9, 1, 1)
        self.E9 = QtGui.QRadioButton(self.layoutWidget)
        self.E9.setText(_fromUtf8(""))
        self.E9.setAutoExclusive(False)
        self.E9.setObjectName(_fromUtf8("E9"))
        self.gridLayout.addWidget(self.E9, 5, 9, 1, 1)
        self.E7 = QtGui.QRadioButton(self.layoutWidget)
        self.E7.setText(_fromUtf8(""))
        self.E7.setAutoExclusive(False)
        self.E7.setObjectName(_fromUtf8("E7"))
        self.gridLayout.addWidget(self.E7, 5, 7, 1, 1)
        self.F1 = QtGui.QRadioButton(self.layoutWidget)
        self.F1.setText(_fromUtf8(""))
        self.F1.setAutoExclusive(False)
        self.F1.setObjectName(_fromUtf8("F1"))
        self.gridLayout.addWidget(self.F1, 6, 1, 1, 1)
        self.F6 = QtGui.QRadioButton(self.layoutWidget)
        self.F6.setText(_fromUtf8(""))
        self.F6.setAutoExclusive(False)
        self.F6.setObjectName(_fromUtf8("F6"))
        self.gridLayout.addWidget(self.F6, 6, 6, 1, 1)
        self.F7 = QtGui.QRadioButton(self.layoutWidget)
        self.F7.setText(_fromUtf8(""))
        self.F7.setAutoExclusive(False)
        self.F7.setObjectName(_fromUtf8("F7"))
        self.gridLayout.addWidget(self.F7, 6, 7, 1, 1)
        self.F5 = QtGui.QRadioButton(self.layoutWidget)
        self.F5.setText(_fromUtf8(""))
        self.F5.setAutoExclusive(False)
        self.F5.setObjectName(_fromUtf8("F5"))
        self.gridLayout.addWidget(self.F5, 6, 5, 1, 1)
        self.G2 = QtGui.QRadioButton(self.layoutWidget)
        self.G2.setText(_fromUtf8(""))
        self.G2.setAutoExclusive(False)
        self.G2.setObjectName(_fromUtf8("G2"))
        self.gridLayout.addWidget(self.G2, 7, 2, 1, 1)
        self.F3 = QtGui.QRadioButton(self.layoutWidget)
        self.F3.setText(_fromUtf8(""))
        self.F3.setAutoExclusive(False)
        self.F3.setObjectName(_fromUtf8("F3"))
        self.gridLayout.addWidget(self.F3, 6, 3, 1, 1)
        self.F10 = QtGui.QRadioButton(self.layoutWidget)
        self.F10.setText(_fromUtf8(""))
        self.F10.setAutoExclusive(False)
        self.F10.setObjectName(_fromUtf8("F10"))
        self.gridLayout.addWidget(self.F10, 6, 10, 1, 1)
        self.G3 = QtGui.QRadioButton(self.layoutWidget)
        self.G3.setText(_fromUtf8(""))
        self.G3.setAutoExclusive(False)
        self.G3.setObjectName(_fromUtf8("G3"))
        self.gridLayout.addWidget(self.G3, 7, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.F12 = QtGui.QRadioButton(self.layoutWidget)
        self.F12.setText(_fromUtf8(""))
        self.F12.setAutoExclusive(False)
        self.F12.setObjectName(_fromUtf8("F12"))
        self.gridLayout.addWidget(self.F12, 6, 12, 1, 1)
        self.G6 = QtGui.QRadioButton(self.layoutWidget)
        self.G6.setText(_fromUtf8(""))
        self.G6.setAutoExclusive(False)
        self.G6.setObjectName(_fromUtf8("G6"))
        self.gridLayout.addWidget(self.G6, 7, 6, 1, 1)
        self.G7 = QtGui.QRadioButton(self.layoutWidget)
        self.G7.setText(_fromUtf8(""))
        self.G7.setAutoExclusive(False)
        self.G7.setObjectName(_fromUtf8("G7"))
        self.gridLayout.addWidget(self.G7, 7, 7, 1, 1)
        self.F11 = QtGui.QRadioButton(self.layoutWidget)
        self.F11.setText(_fromUtf8(""))
        self.F11.setAutoExclusive(False)
        self.F11.setObjectName(_fromUtf8("F11"))
        self.gridLayout.addWidget(self.F11, 6, 11, 1, 1)
        self.F4 = QtGui.QRadioButton(self.layoutWidget)
        self.F4.setText(_fromUtf8(""))
        self.F4.setAutoExclusive(False)
        self.F4.setObjectName(_fromUtf8("F4"))
        self.gridLayout.addWidget(self.F4, 6, 4, 1, 1)
        self.G1 = QtGui.QRadioButton(self.layoutWidget)
        self.G1.setText(_fromUtf8(""))
        self.G1.setAutoExclusive(False)
        self.G1.setObjectName(_fromUtf8("G1"))
        self.gridLayout.addWidget(self.G1, 7, 1, 1, 1)
        self.H4 = QtGui.QRadioButton(self.layoutWidget)
        self.H4.setText(_fromUtf8(""))
        self.H4.setAutoExclusive(False)
        self.H4.setObjectName(_fromUtf8("H4"))
        self.gridLayout.addWidget(self.H4, 8, 4, 1, 1)
        self.H7 = QtGui.QRadioButton(self.layoutWidget)
        self.H7.setText(_fromUtf8(""))
        self.H7.setAutoExclusive(False)
        self.H7.setObjectName(_fromUtf8("H7"))
        self.gridLayout.addWidget(self.H7, 8, 7, 1, 1)
        self.G12 = QtGui.QRadioButton(self.layoutWidget)
        self.G12.setText(_fromUtf8(""))
        self.G12.setAutoExclusive(False)
        self.G12.setObjectName(_fromUtf8("G12"))
        self.gridLayout.addWidget(self.G12, 7, 12, 1, 1)
        self.G10 = QtGui.QRadioButton(self.layoutWidget)
        self.G10.setText(_fromUtf8(""))
        self.G10.setAutoExclusive(False)
        self.G10.setObjectName(_fromUtf8("G10"))
        self.gridLayout.addWidget(self.G10, 7, 10, 1, 1)
        self.H6 = QtGui.QRadioButton(self.layoutWidget)
        self.H6.setText(_fromUtf8(""))
        self.H6.setAutoExclusive(False)
        self.H6.setObjectName(_fromUtf8("H6"))
        self.gridLayout.addWidget(self.H6, 8, 6, 1, 1)
        self.H5 = QtGui.QRadioButton(self.layoutWidget)
        self.H5.setText(_fromUtf8(""))
        self.H5.setAutoExclusive(False)
        self.H5.setObjectName(_fromUtf8("H5"))
        self.gridLayout.addWidget(self.H5, 8, 5, 1, 1)
        self.H11 = QtGui.QRadioButton(self.layoutWidget)
        self.H11.setText(_fromUtf8(""))
        self.H11.setAutoExclusive(False)
        self.H11.setObjectName(_fromUtf8("H11"))
        self.gridLayout.addWidget(self.H11, 8, 11, 1, 1)
        self.H2 = QtGui.QRadioButton(self.layoutWidget)
        self.H2.setText(_fromUtf8(""))
        self.H2.setAutoExclusive(False)
        self.H2.setObjectName(_fromUtf8("H2"))
        self.gridLayout.addWidget(self.H2, 8, 2, 1, 1)
        self.H9 = QtGui.QRadioButton(self.layoutWidget)
        self.H9.setText(_fromUtf8(""))
        self.H9.setAutoExclusive(False)
        self.H9.setObjectName(_fromUtf8("H9"))
        self.gridLayout.addWidget(self.H9, 8, 9, 1, 1)
        self.H12 = QtGui.QRadioButton(self.layoutWidget)
        self.H12.setText(_fromUtf8(""))
        self.H12.setAutoExclusive(False)
        self.H12.setObjectName(_fromUtf8("H12"))
        self.gridLayout.addWidget(self.H12, 8, 12, 1, 1)
        self.H10 = QtGui.QRadioButton(self.layoutWidget)
        self.H10.setText(_fromUtf8(""))
        self.H10.setAutoExclusive(False)
        self.H10.setObjectName(_fromUtf8("H10"))
        self.gridLayout.addWidget(self.H10, 8, 10, 1, 1)
        self.H8 = QtGui.QRadioButton(self.layoutWidget)
        self.H8.setText(_fromUtf8(""))
        self.H8.setAutoExclusive(False)
        self.H8.setObjectName(_fromUtf8("H8"))
        self.gridLayout.addWidget(self.H8, 8, 8, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.G11 = QtGui.QRadioButton(self.layoutWidget)
        self.G11.setText(_fromUtf8(""))
        self.G11.setAutoExclusive(False)
        self.G11.setObjectName(_fromUtf8("G11"))
        self.gridLayout.addWidget(self.G11, 7, 11, 1, 1)
        self.H1 = QtGui.QRadioButton(self.layoutWidget)
        self.H1.setText(_fromUtf8(""))
        self.H1.setAutoExclusive(False)
        self.H1.setObjectName(_fromUtf8("H1"))
        self.gridLayout.addWidget(self.H1, 8, 1, 1, 1)
        self.H3 = QtGui.QRadioButton(self.layoutWidget)
        self.H3.setText(_fromUtf8(""))
        self.H3.setAutoExclusive(False)
        self.H3.setObjectName(_fromUtf8("H3"))
        self.gridLayout.addWidget(self.H3, 8, 3, 1, 1)
        self.line_2 = QtGui.QFrame(self)
        self.line_2.setGeometry(QtCore.QRect(10, 290, 771, 16))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.setWindowTitle(_translate("Well Plate Menu", "Well Plate Menu", None))
        self.absButton.setText(_translate("Well Plate Menu", "Absorbance", None))
        self.absSpecButton.setText(_translate("Well Plate Menu", "Absorbace\n"
" Spectrum", None))
        self.flrButton.setText(_translate("Well Plate Menu", "Flourescent \n"
"  Intensity", None))
        self.flrSpecButton.setText(_translate("Well Plate Menu", "Flourescence \n"
"  Spectrum", None))
        self.shakeButton.setText(_translate("Well Plate Menu", "Shaking", None))
        self.kineticsButton.setText(_translate("Well Plate Menu", "Kinetics", None))
        self.protocolLabel.setPlaceholderText(_translate("Well Plate Menu", "Protocol Label", None))
        self.clearWellsButton.setText(_translate("Well Plate Menu", "Clear Wells", None))
        self.deletePlateButton.setText(_translate("Well Plate Menu", "Delete Plate", None))
        self.label_9.setText(_translate("Well Plate Menu", "1", None))
        self.label_10.setText(_translate("Well Plate Menu", "2", None))
        self.label_11.setText(_translate("Well Plate Menu", "3", None))
        self.label_12.setText(_translate("Well Plate Menu", "4", None))
        self.label_13.setText(_translate("Well Plate Menu", "5", None))
        self.label_15.setText(_translate("Well Plate Menu", "7", None))
        self.label_20.setText(_translate("Well Plate Menu", "12", None))
        self.label_18.setText(_translate("Well Plate Menu", "10", None))
        self.label.setText(_translate("Well Plate Menu", "A", None))
        self.label_14.setText(_translate("Well Plate Menu", "6", None))
        self.label_19.setText(_translate("Well Plate Menu", "11", None))
        self.label_16.setText(_translate("Well Plate Menu", "8", None))
        self.label_17.setText(_translate("Well Plate Menu", "9", None))
        self.label_2.setText(_translate("Well Plate Menu", "B", None))
        self.label_5.setText(_translate("Well Plate Menu", "E", None))
        self.label_3.setText(_translate("Well Plate Menu", "C", None))
        self.label_4.setText(_translate("Well Plate Menu", "D", None))
        self.label_7.setText(_translate("Well Plate Menu", "G", None))
        self.label_6.setText(_translate("Well Plate Menu", "F", None))
        self.label_8.setText(_translate("Well Plate Menu", "H", None))

