# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replacement_well_menu.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(788, 306)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("absorbanceLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("absSpectrumLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("flourescenceLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("flrSpectrumLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("shakeLogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(660, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("886e08dc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 230, 771, 16))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(400, 90, 241, 21))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton_7 = QtGui.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(400, 130, 241, 31))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(400, 180, 241, 31))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(760, 10, 21, 21))
        self.pushButton_9.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("x-mark-4-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon6)
        self.pushButton_9.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 11, 351, 221))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 5, 1, 1)
        self.radioButton_38 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_38.setText(_fromUtf8(""))
        self.radioButton_38.setAutoExclusive(False)
        self.radioButton_38.setObjectName(_fromUtf8("radioButton_38"))
        self.gridLayout.addWidget(self.radioButton_38, 2, 5, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton.setText(_fromUtf8(""))
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 1, 1, 1, 1)
        self.radioButton_70 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_70.setText(_fromUtf8(""))
        self.radioButton_70.setAutoExclusive(False)
        self.radioButton_70.setObjectName(_fromUtf8("radioButton_70"))
        self.gridLayout.addWidget(self.radioButton_70, 2, 9, 1, 1)
        self.radioButton_14 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_14.setText(_fromUtf8(""))
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.gridLayout.addWidget(self.radioButton_14, 2, 2, 1, 1)
        self.radioButton_72 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_72.setText(_fromUtf8(""))
        self.radioButton_72.setAutoExclusive(False)
        self.radioButton_72.setObjectName(_fromUtf8("radioButton_72"))
        self.gridLayout.addWidget(self.radioButton_72, 1, 9, 1, 1)
        self.radioButton_30 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_30.setText(_fromUtf8(""))
        self.radioButton_30.setAutoExclusive(False)
        self.radioButton_30.setObjectName(_fromUtf8("radioButton_30"))
        self.gridLayout.addWidget(self.radioButton_30, 2, 4, 1, 1)
        self.radioButton_16 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_16.setText(_fromUtf8(""))
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.gridLayout.addWidget(self.radioButton_16, 1, 2, 1, 1)
        self.radioButton_54 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_54.setText(_fromUtf8(""))
        self.radioButton_54.setAutoExclusive(False)
        self.radioButton_54.setObjectName(_fromUtf8("radioButton_54"))
        self.gridLayout.addWidget(self.radioButton_54, 2, 7, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 7, 1, 1)
        self.radioButton_78 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_78.setText(_fromUtf8(""))
        self.radioButton_78.setAutoExclusive(False)
        self.radioButton_78.setObjectName(_fromUtf8("radioButton_78"))
        self.gridLayout.addWidget(self.radioButton_78, 2, 10, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 0, 12, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_2.setText(_fromUtf8(""))
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout.addWidget(self.radioButton_2, 2, 1, 1, 1)
        self.radioButton_86 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_86.setText(_fromUtf8(""))
        self.radioButton_86.setAutoExclusive(False)
        self.radioButton_86.setObjectName(_fromUtf8("radioButton_86"))
        self.gridLayout.addWidget(self.radioButton_86, 2, 11, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 10, 1, 1)
        self.radioButton_56 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_56.setText(_fromUtf8(""))
        self.radioButton_56.setAutoExclusive(False)
        self.radioButton_56.setObjectName(_fromUtf8("radioButton_56"))
        self.gridLayout.addWidget(self.radioButton_56, 1, 7, 1, 1)
        self.radioButton_64 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_64.setText(_fromUtf8(""))
        self.radioButton_64.setAutoExclusive(False)
        self.radioButton_64.setObjectName(_fromUtf8("radioButton_64"))
        self.gridLayout.addWidget(self.radioButton_64, 1, 8, 1, 1)
        self.radioButton_46 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_46.setText(_fromUtf8(""))
        self.radioButton_46.setAutoExclusive(False)
        self.radioButton_46.setObjectName(_fromUtf8("radioButton_46"))
        self.gridLayout.addWidget(self.radioButton_46, 2, 6, 1, 1)
        self.radioButton_22 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_22.setText(_fromUtf8(""))
        self.radioButton_22.setAutoExclusive(False)
        self.radioButton_22.setObjectName(_fromUtf8("radioButton_22"))
        self.gridLayout.addWidget(self.radioButton_22, 2, 3, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.radioButton_32 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_32.setText(_fromUtf8(""))
        self.radioButton_32.setAutoExclusive(False)
        self.radioButton_32.setObjectName(_fromUtf8("radioButton_32"))
        self.gridLayout.addWidget(self.radioButton_32, 1, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 6, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 0, 11, 1, 1)
        self.radioButton_24 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_24.setText(_fromUtf8(""))
        self.radioButton_24.setAutoExclusive(False)
        self.radioButton_24.setObjectName(_fromUtf8("radioButton_24"))
        self.gridLayout.addWidget(self.radioButton_24, 1, 3, 1, 1)
        self.radioButton_40 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_40.setText(_fromUtf8(""))
        self.radioButton_40.setAutoExclusive(False)
        self.radioButton_40.setObjectName(_fromUtf8("radioButton_40"))
        self.gridLayout.addWidget(self.radioButton_40, 1, 5, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 0, 8, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 0, 9, 1, 1)
        self.radioButton_48 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_48.setText(_fromUtf8(""))
        self.radioButton_48.setAutoExclusive(False)
        self.radioButton_48.setObjectName(_fromUtf8("radioButton_48"))
        self.gridLayout.addWidget(self.radioButton_48, 1, 6, 1, 1)
        self.radioButton_80 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_80.setText(_fromUtf8(""))
        self.radioButton_80.setAutoExclusive(False)
        self.radioButton_80.setObjectName(_fromUtf8("radioButton_80"))
        self.gridLayout.addWidget(self.radioButton_80, 1, 10, 1, 1)
        self.radioButton_88 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_88.setText(_fromUtf8(""))
        self.radioButton_88.setAutoExclusive(False)
        self.radioButton_88.setObjectName(_fromUtf8("radioButton_88"))
        self.gridLayout.addWidget(self.radioButton_88, 1, 11, 1, 1)
        self.radioButton_96 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_96.setText(_fromUtf8(""))
        self.radioButton_96.setAutoExclusive(False)
        self.radioButton_96.setObjectName(_fromUtf8("radioButton_96"))
        self.gridLayout.addWidget(self.radioButton_96, 1, 12, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.radioButton_62 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_62.setText(_fromUtf8(""))
        self.radioButton_62.setAutoExclusive(False)
        self.radioButton_62.setObjectName(_fromUtf8("radioButton_62"))
        self.gridLayout.addWidget(self.radioButton_62, 2, 8, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.radioButton_15 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_15.setText(_fromUtf8(""))
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.gridLayout.addWidget(self.radioButton_15, 5, 2, 1, 1)
        self.radioButton_74 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_74.setText(_fromUtf8(""))
        self.radioButton_74.setAutoExclusive(False)
        self.radioButton_74.setObjectName(_fromUtf8("radioButton_74"))
        self.gridLayout.addWidget(self.radioButton_74, 3, 10, 1, 1)
        self.radioButton_81 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_81.setText(_fromUtf8(""))
        self.radioButton_81.setAutoExclusive(False)
        self.radioButton_81.setObjectName(_fromUtf8("radioButton_81"))
        self.gridLayout.addWidget(self.radioButton_81, 4, 11, 1, 1)
        self.radioButton_34 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_34.setText(_fromUtf8(""))
        self.radioButton_34.setAutoExclusive(False)
        self.radioButton_34.setObjectName(_fromUtf8("radioButton_34"))
        self.gridLayout.addWidget(self.radioButton_34, 3, 5, 1, 1)
        self.radioButton_33 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_33.setText(_fromUtf8(""))
        self.radioButton_33.setAutoExclusive(False)
        self.radioButton_33.setObjectName(_fromUtf8("radioButton_33"))
        self.gridLayout.addWidget(self.radioButton_33, 4, 5, 1, 1)
        self.radioButton_5 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_5.setText(_fromUtf8(""))
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.gridLayout.addWidget(self.radioButton_5, 5, 1, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_3.setText(_fromUtf8(""))
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout.addWidget(self.radioButton_3, 3, 1, 1, 1)
        self.radioButton_23 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_23.setText(_fromUtf8(""))
        self.radioButton_23.setAutoExclusive(False)
        self.radioButton_23.setObjectName(_fromUtf8("radioButton_23"))
        self.gridLayout.addWidget(self.radioButton_23, 5, 3, 1, 1)
        self.radioButton_31 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_31.setText(_fromUtf8(""))
        self.radioButton_31.setAutoExclusive(False)
        self.radioButton_31.setObjectName(_fromUtf8("radioButton_31"))
        self.gridLayout.addWidget(self.radioButton_31, 5, 4, 1, 1)
        self.radioButton_90 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_90.setText(_fromUtf8(""))
        self.radioButton_90.setAutoExclusive(False)
        self.radioButton_90.setObjectName(_fromUtf8("radioButton_90"))
        self.gridLayout.addWidget(self.radioButton_90, 3, 12, 1, 1)
        self.radioButton_26 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_26.setText(_fromUtf8(""))
        self.radioButton_26.setAutoExclusive(False)
        self.radioButton_26.setObjectName(_fromUtf8("radioButton_26"))
        self.gridLayout.addWidget(self.radioButton_26, 3, 4, 1, 1)
        self.radioButton_18 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_18.setText(_fromUtf8(""))
        self.radioButton_18.setAutoExclusive(False)
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.gridLayout.addWidget(self.radioButton_18, 3, 3, 1, 1)
        self.radioButton_17 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_17.setText(_fromUtf8(""))
        self.radioButton_17.setAutoExclusive(False)
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.gridLayout.addWidget(self.radioButton_17, 4, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.radioButton_66 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_66.setText(_fromUtf8(""))
        self.radioButton_66.setAutoExclusive(False)
        self.radioButton_66.setObjectName(_fromUtf8("radioButton_66"))
        self.gridLayout.addWidget(self.radioButton_66, 3, 9, 1, 1)
        self.radioButton_42 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_42.setText(_fromUtf8(""))
        self.radioButton_42.setAutoExclusive(False)
        self.radioButton_42.setObjectName(_fromUtf8("radioButton_42"))
        self.gridLayout.addWidget(self.radioButton_42, 3, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_4.setText(_fromUtf8(""))
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout.addWidget(self.radioButton_4, 4, 1, 1, 1)
        self.radioButton_82 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_82.setText(_fromUtf8(""))
        self.radioButton_82.setAutoExclusive(False)
        self.radioButton_82.setObjectName(_fromUtf8("radioButton_82"))
        self.gridLayout.addWidget(self.radioButton_82, 3, 11, 1, 1)
        self.radioButton_10 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_10.setText(_fromUtf8(""))
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.gridLayout.addWidget(self.radioButton_10, 3, 2, 1, 1)
        self.radioButton_58 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_58.setText(_fromUtf8(""))
        self.radioButton_58.setAutoExclusive(False)
        self.radioButton_58.setObjectName(_fromUtf8("radioButton_58"))
        self.gridLayout.addWidget(self.radioButton_58, 3, 8, 1, 1)
        self.radioButton_9 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_9.setText(_fromUtf8(""))
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.gridLayout.addWidget(self.radioButton_9, 4, 2, 1, 1)
        self.radioButton_25 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_25.setText(_fromUtf8(""))
        self.radioButton_25.setAutoExclusive(False)
        self.radioButton_25.setObjectName(_fromUtf8("radioButton_25"))
        self.gridLayout.addWidget(self.radioButton_25, 4, 4, 1, 1)
        self.radioButton_41 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_41.setText(_fromUtf8(""))
        self.radioButton_41.setAutoExclusive(False)
        self.radioButton_41.setObjectName(_fromUtf8("radioButton_41"))
        self.gridLayout.addWidget(self.radioButton_41, 4, 6, 1, 1)
        self.radioButton_49 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_49.setText(_fromUtf8(""))
        self.radioButton_49.setAutoExclusive(False)
        self.radioButton_49.setObjectName(_fromUtf8("radioButton_49"))
        self.gridLayout.addWidget(self.radioButton_49, 4, 7, 1, 1)
        self.radioButton_57 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_57.setText(_fromUtf8(""))
        self.radioButton_57.setAutoExclusive(False)
        self.radioButton_57.setObjectName(_fromUtf8("radioButton_57"))
        self.gridLayout.addWidget(self.radioButton_57, 4, 8, 1, 1)
        self.radioButton_65 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_65.setText(_fromUtf8(""))
        self.radioButton_65.setAutoExclusive(False)
        self.radioButton_65.setObjectName(_fromUtf8("radioButton_65"))
        self.gridLayout.addWidget(self.radioButton_65, 4, 9, 1, 1)
        self.radioButton_94 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_94.setText(_fromUtf8(""))
        self.radioButton_94.setAutoExclusive(False)
        self.radioButton_94.setObjectName(_fromUtf8("radioButton_94"))
        self.gridLayout.addWidget(self.radioButton_94, 2, 12, 1, 1)
        self.radioButton_73 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_73.setText(_fromUtf8(""))
        self.radioButton_73.setAutoExclusive(False)
        self.radioButton_73.setObjectName(_fromUtf8("radioButton_73"))
        self.gridLayout.addWidget(self.radioButton_73, 4, 10, 1, 1)
        self.radioButton_50 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_50.setText(_fromUtf8(""))
        self.radioButton_50.setAutoExclusive(False)
        self.radioButton_50.setObjectName(_fromUtf8("radioButton_50"))
        self.gridLayout.addWidget(self.radioButton_50, 3, 7, 1, 1)
        self.radioButton_89 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_89.setText(_fromUtf8(""))
        self.radioButton_89.setAutoExclusive(False)
        self.radioButton_89.setObjectName(_fromUtf8("radioButton_89"))
        self.gridLayout.addWidget(self.radioButton_89, 4, 12, 1, 1)
        self.radioButton_29 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_29.setText(_fromUtf8(""))
        self.radioButton_29.setAutoExclusive(False)
        self.radioButton_29.setObjectName(_fromUtf8("radioButton_29"))
        self.gridLayout.addWidget(self.radioButton_29, 7, 4, 1, 1)
        self.radioButton_79 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_79.setText(_fromUtf8(""))
        self.radioButton_79.setAutoExclusive(False)
        self.radioButton_79.setObjectName(_fromUtf8("radioButton_79"))
        self.gridLayout.addWidget(self.radioButton_79, 5, 10, 1, 1)
        self.radioButton_39 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_39.setText(_fromUtf8(""))
        self.radioButton_39.setAutoExclusive(False)
        self.radioButton_39.setObjectName(_fromUtf8("radioButton_39"))
        self.gridLayout.addWidget(self.radioButton_39, 5, 5, 1, 1)
        self.radioButton_47 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_47.setText(_fromUtf8(""))
        self.radioButton_47.setAutoExclusive(False)
        self.radioButton_47.setObjectName(_fromUtf8("radioButton_47"))
        self.gridLayout.addWidget(self.radioButton_47, 5, 6, 1, 1)
        self.radioButton_95 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_95.setText(_fromUtf8(""))
        self.radioButton_95.setAutoExclusive(False)
        self.radioButton_95.setObjectName(_fromUtf8("radioButton_95"))
        self.gridLayout.addWidget(self.radioButton_95, 5, 12, 1, 1)
        self.radioButton_59 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_59.setText(_fromUtf8(""))
        self.radioButton_59.setAutoExclusive(False)
        self.radioButton_59.setObjectName(_fromUtf8("radioButton_59"))
        self.gridLayout.addWidget(self.radioButton_59, 6, 8, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.radioButton_87 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_87.setText(_fromUtf8(""))
        self.radioButton_87.setAutoExclusive(False)
        self.radioButton_87.setObjectName(_fromUtf8("radioButton_87"))
        self.gridLayout.addWidget(self.radioButton_87, 5, 11, 1, 1)
        self.radioButton_37 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_37.setText(_fromUtf8(""))
        self.radioButton_37.setAutoExclusive(False)
        self.radioButton_37.setObjectName(_fromUtf8("radioButton_37"))
        self.gridLayout.addWidget(self.radioButton_37, 7, 5, 1, 1)
        self.radioButton_61 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_61.setText(_fromUtf8(""))
        self.radioButton_61.setAutoExclusive(False)
        self.radioButton_61.setObjectName(_fromUtf8("radioButton_61"))
        self.gridLayout.addWidget(self.radioButton_61, 7, 8, 1, 1)
        self.radioButton_11 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_11.setText(_fromUtf8(""))
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.gridLayout.addWidget(self.radioButton_11, 6, 2, 1, 1)
        self.radioButton_69 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_69.setText(_fromUtf8(""))
        self.radioButton_69.setAutoExclusive(False)
        self.radioButton_69.setObjectName(_fromUtf8("radioButton_69"))
        self.gridLayout.addWidget(self.radioButton_69, 7, 9, 1, 1)
        self.radioButton_63 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_63.setText(_fromUtf8(""))
        self.radioButton_63.setAutoExclusive(False)
        self.radioButton_63.setObjectName(_fromUtf8("radioButton_63"))
        self.gridLayout.addWidget(self.radioButton_63, 5, 8, 1, 1)
        self.radioButton_67 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_67.setText(_fromUtf8(""))
        self.radioButton_67.setAutoExclusive(False)
        self.radioButton_67.setObjectName(_fromUtf8("radioButton_67"))
        self.gridLayout.addWidget(self.radioButton_67, 6, 9, 1, 1)
        self.radioButton_71 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_71.setText(_fromUtf8(""))
        self.radioButton_71.setAutoExclusive(False)
        self.radioButton_71.setObjectName(_fromUtf8("radioButton_71"))
        self.gridLayout.addWidget(self.radioButton_71, 5, 9, 1, 1)
        self.radioButton_55 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_55.setText(_fromUtf8(""))
        self.radioButton_55.setAutoExclusive(False)
        self.radioButton_55.setObjectName(_fromUtf8("radioButton_55"))
        self.gridLayout.addWidget(self.radioButton_55, 5, 7, 1, 1)
        self.radioButton_6 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_6.setText(_fromUtf8(""))
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.gridLayout.addWidget(self.radioButton_6, 6, 1, 1, 1)
        self.radioButton_43 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_43.setText(_fromUtf8(""))
        self.radioButton_43.setAutoExclusive(False)
        self.radioButton_43.setObjectName(_fromUtf8("radioButton_43"))
        self.gridLayout.addWidget(self.radioButton_43, 6, 6, 1, 1)
        self.radioButton_51 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_51.setText(_fromUtf8(""))
        self.radioButton_51.setAutoExclusive(False)
        self.radioButton_51.setObjectName(_fromUtf8("radioButton_51"))
        self.gridLayout.addWidget(self.radioButton_51, 6, 7, 1, 1)
        self.radioButton_35 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_35.setText(_fromUtf8(""))
        self.radioButton_35.setAutoExclusive(False)
        self.radioButton_35.setObjectName(_fromUtf8("radioButton_35"))
        self.gridLayout.addWidget(self.radioButton_35, 6, 5, 1, 1)
        self.radioButton_13 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_13.setText(_fromUtf8(""))
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.gridLayout.addWidget(self.radioButton_13, 7, 2, 1, 1)
        self.radioButton_19 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_19.setText(_fromUtf8(""))
        self.radioButton_19.setAutoExclusive(False)
        self.radioButton_19.setObjectName(_fromUtf8("radioButton_19"))
        self.gridLayout.addWidget(self.radioButton_19, 6, 3, 1, 1)
        self.radioButton_75 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_75.setText(_fromUtf8(""))
        self.radioButton_75.setAutoExclusive(False)
        self.radioButton_75.setObjectName(_fromUtf8("radioButton_75"))
        self.gridLayout.addWidget(self.radioButton_75, 6, 10, 1, 1)
        self.radioButton_21 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_21.setText(_fromUtf8(""))
        self.radioButton_21.setAutoExclusive(False)
        self.radioButton_21.setObjectName(_fromUtf8("radioButton_21"))
        self.gridLayout.addWidget(self.radioButton_21, 7, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.radioButton_91 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_91.setText(_fromUtf8(""))
        self.radioButton_91.setAutoExclusive(False)
        self.radioButton_91.setObjectName(_fromUtf8("radioButton_91"))
        self.gridLayout.addWidget(self.radioButton_91, 6, 12, 1, 1)
        self.radioButton_45 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_45.setText(_fromUtf8(""))
        self.radioButton_45.setAutoExclusive(False)
        self.radioButton_45.setObjectName(_fromUtf8("radioButton_45"))
        self.gridLayout.addWidget(self.radioButton_45, 7, 6, 1, 1)
        self.radioButton_53 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_53.setText(_fromUtf8(""))
        self.radioButton_53.setAutoExclusive(False)
        self.radioButton_53.setObjectName(_fromUtf8("radioButton_53"))
        self.gridLayout.addWidget(self.radioButton_53, 7, 7, 1, 1)
        self.radioButton_83 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_83.setText(_fromUtf8(""))
        self.radioButton_83.setAutoExclusive(False)
        self.radioButton_83.setObjectName(_fromUtf8("radioButton_83"))
        self.gridLayout.addWidget(self.radioButton_83, 6, 11, 1, 1)
        self.radioButton_27 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_27.setText(_fromUtf8(""))
        self.radioButton_27.setAutoExclusive(False)
        self.radioButton_27.setObjectName(_fromUtf8("radioButton_27"))
        self.gridLayout.addWidget(self.radioButton_27, 6, 4, 1, 1)
        self.radioButton_7 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_7.setText(_fromUtf8(""))
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.gridLayout.addWidget(self.radioButton_7, 7, 1, 1, 1)
        self.radioButton_28 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_28.setText(_fromUtf8(""))
        self.radioButton_28.setAutoExclusive(False)
        self.radioButton_28.setObjectName(_fromUtf8("radioButton_28"))
        self.gridLayout.addWidget(self.radioButton_28, 8, 4, 1, 1)
        self.radioButton_52 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_52.setText(_fromUtf8(""))
        self.radioButton_52.setAutoExclusive(False)
        self.radioButton_52.setObjectName(_fromUtf8("radioButton_52"))
        self.gridLayout.addWidget(self.radioButton_52, 8, 7, 1, 1)
        self.radioButton_93 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_93.setText(_fromUtf8(""))
        self.radioButton_93.setAutoExclusive(False)
        self.radioButton_93.setObjectName(_fromUtf8("radioButton_93"))
        self.gridLayout.addWidget(self.radioButton_93, 7, 12, 1, 1)
        self.radioButton_77 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_77.setText(_fromUtf8(""))
        self.radioButton_77.setAutoExclusive(False)
        self.radioButton_77.setObjectName(_fromUtf8("radioButton_77"))
        self.gridLayout.addWidget(self.radioButton_77, 7, 10, 1, 1)
        self.radioButton_44 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_44.setText(_fromUtf8(""))
        self.radioButton_44.setAutoExclusive(False)
        self.radioButton_44.setObjectName(_fromUtf8("radioButton_44"))
        self.gridLayout.addWidget(self.radioButton_44, 8, 6, 1, 1)
        self.radioButton_36 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_36.setText(_fromUtf8(""))
        self.radioButton_36.setAutoExclusive(False)
        self.radioButton_36.setObjectName(_fromUtf8("radioButton_36"))
        self.gridLayout.addWidget(self.radioButton_36, 8, 5, 1, 1)
        self.radioButton_84 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_84.setText(_fromUtf8(""))
        self.radioButton_84.setAutoExclusive(False)
        self.radioButton_84.setObjectName(_fromUtf8("radioButton_84"))
        self.gridLayout.addWidget(self.radioButton_84, 8, 11, 1, 1)
        self.radioButton_12 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_12.setText(_fromUtf8(""))
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.gridLayout.addWidget(self.radioButton_12, 8, 2, 1, 1)
        self.radioButton_68 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_68.setText(_fromUtf8(""))
        self.radioButton_68.setAutoExclusive(False)
        self.radioButton_68.setObjectName(_fromUtf8("radioButton_68"))
        self.gridLayout.addWidget(self.radioButton_68, 8, 9, 1, 1)
        self.radioButton_92 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_92.setText(_fromUtf8(""))
        self.radioButton_92.setAutoExclusive(False)
        self.radioButton_92.setObjectName(_fromUtf8("radioButton_92"))
        self.gridLayout.addWidget(self.radioButton_92, 8, 12, 1, 1)
        self.radioButton_76 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_76.setText(_fromUtf8(""))
        self.radioButton_76.setAutoExclusive(False)
        self.radioButton_76.setObjectName(_fromUtf8("radioButton_76"))
        self.gridLayout.addWidget(self.radioButton_76, 8, 10, 1, 1)
        self.radioButton_60 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_60.setText(_fromUtf8(""))
        self.radioButton_60.setAutoExclusive(False)
        self.radioButton_60.setObjectName(_fromUtf8("radioButton_60"))
        self.gridLayout.addWidget(self.radioButton_60, 8, 8, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.radioButton_85 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_85.setText(_fromUtf8(""))
        self.radioButton_85.setAutoExclusive(False)
        self.radioButton_85.setObjectName(_fromUtf8("radioButton_85"))
        self.gridLayout.addWidget(self.radioButton_85, 7, 11, 1, 1)
        self.radioButton_8 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_8.setText(_fromUtf8(""))
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.gridLayout.addWidget(self.radioButton_8, 8, 1, 1, 1)
        self.radioButton_20 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_20.setText(_fromUtf8(""))
        self.radioButton_20.setAutoExclusive(False)
        self.radioButton_20.setObjectName(_fromUtf8("radioButton_20"))
        self.gridLayout.addWidget(self.radioButton_20, 8, 3, 1, 1)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 290, 771, 16))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton.setText(_translate("Form", "Absorbance", None))
        self.pushButton_2.setText(_translate("Form", "Absorbace\n"
" Spectrum", None))
        self.pushButton_3.setText(_translate("Form", "Flourescent \n"
"  Intensity", None))
        self.pushButton_4.setText(_translate("Form", "Flourescence \n"
"  Spectrum", None))
        self.pushButton_5.setText(_translate("Form", "Shaking", None))
        self.pushButton_6.setText(_translate("Form", "Kinetics", None))
        self.lineEdit.setPlaceholderText(_translate("Form", "Protocol Label", None))
        self.pushButton_7.setText(_translate("Form", "Clear Wells", None))
        self.pushButton_8.setText(_translate("Form", "Delete Plate", None))
        self.label_9.setText(_translate("Form", "1", None))
        self.label_10.setText(_translate("Form", "2", None))
        self.label_11.setText(_translate("Form", "3", None))
        self.label_12.setText(_translate("Form", "4", None))
        self.label_13.setText(_translate("Form", "5", None))
        self.label_15.setText(_translate("Form", "7", None))
        self.label_20.setText(_translate("Form", "12", None))
        self.label_18.setText(_translate("Form", "10", None))
        self.label.setText(_translate("Form", "A", None))
        self.label_14.setText(_translate("Form", "6", None))
        self.label_19.setText(_translate("Form", "11", None))
        self.label_16.setText(_translate("Form", "8", None))
        self.label_17.setText(_translate("Form", "9", None))
        self.label_2.setText(_translate("Form", "B", None))
        self.label_5.setText(_translate("Form", "E", None))
        self.label_3.setText(_translate("Form", "C", None))
        self.label_4.setText(_translate("Form", "D", None))
        self.label_7.setText(_translate("Form", "G", None))
        self.label_6.setText(_translate("Form", "F", None))
        self.label_8.setText(_translate("Form", "H", None))

