# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flrMenu.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(794, 430)
        Form.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 60, 651, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 491, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.exposureTimeSpinBox = QtGui.QSpinBox(Form)
        self.exposureTimeSpinBox.setGeometry(QtCore.QRect(260, 100, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(20)
        self.exposureTimeSpinBox.setFont(font)
        self.exposureTimeSpinBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.exposureTimeSpinBox.setMinimum(1)
        self.exposureTimeSpinBox.setMaximum(6500)
        self.exposureTimeSpinBox.setObjectName(_fromUtf8("exposureTimeSpinBox"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 251, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(390, 100, 71, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 311, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(460, 170, 81, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.finishButton = QtGui.QPushButton(Form)
        self.finishButton.setGeometry(QtCore.QRect(600, 330, 181, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.finishButton.setFont(font)
        self.finishButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 57, 43);"))
        self.finishButton.setObjectName(_fromUtf8("finishButton"))
        self.addProtocolButton = QtGui.QPushButton(Form)
        self.addProtocolButton.setGeometry(QtCore.QRect(410, 330, 181, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.addProtocolButton.setFont(font)
        self.addProtocolButton.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 127);"))
        self.addProtocolButton.setObjectName(_fromUtf8("addProtocolButton"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 311, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.emissionWavelengthSpinBox = QtGui.QSpinBox(Form)
        self.emissionWavelengthSpinBox.setGeometry(QtCore.QRect(340, 230, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(20)
        self.emissionWavelengthSpinBox.setFont(font)
        self.emissionWavelengthSpinBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.emissionWavelengthSpinBox.setMinimum(400)
        self.emissionWavelengthSpinBox.setMaximum(700)
        self.emissionWavelengthSpinBox.setObjectName(_fromUtf8("emissionWavelengthSpinBox"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(460, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.excitationWavelengthComboBox = QtGui.QComboBox(Form)
        self.excitationWavelengthComboBox.setGeometry(QtCore.QRect(340, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(20)
        self.excitationWavelengthComboBox.setFont(font)
        self.excitationWavelengthComboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 255, 255);"))
        self.excitationWavelengthComboBox.setObjectName(_fromUtf8("excitationWavelengthComboBox"))
        self.excitationWavelengthComboBox.addItem(_fromUtf8(""))
        self.excitationWavelengthComboBox.addItem(_fromUtf8(""))
        self.excitationWavelengthComboBox.addItem(_fromUtf8(""))
        self.line.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.finishButton.raise_()
        self.addProtocolButton.raise_()
        self.exposureTimeSpinBox.raise_()
        self.label_6.raise_()
        self.emissionWavelengthSpinBox.raise_()
        self.label_7.raise_()
        self.excitationWavelengthComboBox.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Flourescent Intensity Settings ", None))
        self.label_2.setText(_translate("Form", "Exposure Time:", None))
        self.label_3.setText(_translate("Form", "(ms)", None))
        self.label_4.setText(_translate("Form", "Excitation Wavelength:", None))
        self.label_5.setText(_translate("Form", "(nm)", None))
        self.finishButton.setText(_translate("Form", "Finish", None))
        self.addProtocolButton.setText(_translate("Form", "Add Protocol", None))
        self.label_6.setText(_translate("Form", "Emission Wavelength:", None))
        self.label_7.setText(_translate("Form", "(nm)", None))
        self.excitationWavelengthComboBox.setItemText(0, _translate("Form", "Blue", None))
        self.excitationWavelengthComboBox.setItemText(1, _translate("Form", "Green", None))
        self.excitationWavelengthComboBox.setItemText(2, _translate("Form", "Orange", None))

