# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wellSelectScreen.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.initUI()
        self.show()

    def initUI(self):
        self.setObjectName(_fromUtf8("Form"))
        self.resize(794, 430)
        self.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);"))
        self.pushButton = QtGui.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(610, 340, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 127);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_118 = QtGui.QLabel(self)
        self.label_118.setGeometry(QtCore.QRect(620, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_118.setFont(font)
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.label_119 = QtGui.QLabel(self)
        self.label_119.setGeometry(QtCore.QRect(610, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_119.setFont(font)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.widget = QtGui.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(20, 20, 551, 381))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_107 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_107.setFont(font)
        self.label_107.setAlignment(QtCore.Qt.AlignCenter)
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout.addWidget(self.label_107, 0, 11, 1, 1)
        self.label_110 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_110.setFont(font)
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.gridLayout.addWidget(self.label_110, 1, 0, 1, 1)
        self.label_98 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_98.setFont(font)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout.addWidget(self.label_98, 0, 2, 1, 1)
        self.label_99 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_99.setFont(font)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout.addWidget(self.label_99, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_100 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_100.setFont(font)
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout.addWidget(self.label_100, 0, 4, 1, 1)
        self.label_103 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_103.setFont(font)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout.addWidget(self.label_103, 0, 7, 1, 1)
        self.label_106 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_106.setFont(font)
        self.label_106.setAlignment(QtCore.Qt.AlignCenter)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout.addWidget(self.label_106, 0, 10, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_101 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_101.setFont(font)
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout.addWidget(self.label_101, 0, 5, 1, 1)
        self.label_108 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_108.setFont(font)
        self.label_108.setAlignment(QtCore.Qt.AlignCenter)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout.addWidget(self.label_108, 0, 12, 1, 1)
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 1, 3, 1, 1)
        self.label_109 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_109.setFont(font)
        self.label_109.setText(_fromUtf8(""))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.gridLayout.addWidget(self.label_109, 0, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.widget)
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 1, 4, 1, 1)
        self.label_105 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_105.setFont(font)
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout.addWidget(self.label_105, 0, 9, 1, 1)
        self.label_102 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_102.setFont(font)
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout.addWidget(self.label_102, 0, 6, 1, 1)
        self.label_104 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_104.setFont(font)
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout.addWidget(self.label_104, 0, 8, 1, 1)
        self.label_46 = QtGui.QLabel(self.widget)
        self.label_46.setText(_fromUtf8(""))
        self.label_46.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout.addWidget(self.label_46, 2, 6, 1, 1)
        self.label_83 = QtGui.QLabel(self.widget)
        self.label_83.setText(_fromUtf8(""))
        self.label_83.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_83.setScaledContents(True)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout.addWidget(self.label_83, 1, 11, 1, 1)
        self.label_43 = QtGui.QLabel(self.widget)
        self.label_43.setText(_fromUtf8(""))
        self.label_43.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 1, 6, 1, 1)
        self.label_22 = QtGui.QLabel(self.widget)
        self.label_22.setText(_fromUtf8(""))
        self.label_22.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 2, 3, 1, 1)
        self.label_62 = QtGui.QLabel(self.widget)
        self.label_62.setText(_fromUtf8(""))
        self.label_62.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout.addWidget(self.label_62, 2, 8, 1, 1)
        self.label_93 = QtGui.QLabel(self.widget)
        self.label_93.setText(_fromUtf8(""))
        self.label_93.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_93.setScaledContents(True)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout.addWidget(self.label_93, 1, 12, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.widget)
        self.label_56.setText(_fromUtf8(""))
        self.label_56.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout.addWidget(self.label_56, 3, 7, 1, 1)
        self.label_64 = QtGui.QLabel(self.widget)
        self.label_64.setText(_fromUtf8(""))
        self.label_64.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_64.setScaledContents(True)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout.addWidget(self.label_64, 3, 8, 1, 1)
        self.label_59 = QtGui.QLabel(self.widget)
        self.label_59.setText(_fromUtf8(""))
        self.label_59.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_59.setScaledContents(True)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout.addWidget(self.label_59, 1, 8, 1, 1)
        self.label_111 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_111.setFont(font)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout.addWidget(self.label_111, 2, 0, 1, 1)
        self.label_78 = QtGui.QLabel(self.widget)
        self.label_78.setText(_fromUtf8(""))
        self.label_78.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_78.setScaledContents(True)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout.addWidget(self.label_78, 2, 10, 1, 1)
        self.label_24 = QtGui.QLabel(self.widget)
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 3, 3, 1, 1)
        self.label_40 = QtGui.QLabel(self.widget)
        self.label_40.setText(_fromUtf8(""))
        self.label_40.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 3, 5, 1, 1)
        self.label_72 = QtGui.QLabel(self.widget)
        self.label_72.setText(_fromUtf8(""))
        self.label_72.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_72.setScaledContents(True)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout.addWidget(self.label_72, 3, 9, 1, 1)
        self.label_80 = QtGui.QLabel(self.widget)
        self.label_80.setText(_fromUtf8(""))
        self.label_80.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_80.setScaledContents(True)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout.addWidget(self.label_80, 3, 10, 1, 1)
        self.label_54 = QtGui.QLabel(self.widget)
        self.label_54.setText(_fromUtf8(""))
        self.label_54.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_54.setScaledContents(True)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout.addWidget(self.label_54, 2, 7, 1, 1)
        self.label_38 = QtGui.QLabel(self.widget)
        self.label_38.setText(_fromUtf8(""))
        self.label_38.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 2, 5, 1, 1)
        self.label_51 = QtGui.QLabel(self.widget)
        self.label_51.setText(_fromUtf8(""))
        self.label_51.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_51.setScaledContents(True)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout.addWidget(self.label_51, 1, 7, 1, 1)
        self.label_90 = QtGui.QLabel(self.widget)
        self.label_90.setText(_fromUtf8(""))
        self.label_90.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_90.setScaledContents(True)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout.addWidget(self.label_90, 2, 12, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_70 = QtGui.QLabel(self.widget)
        self.label_70.setText(_fromUtf8(""))
        self.label_70.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_70.setScaledContents(True)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout.addWidget(self.label_70, 2, 9, 1, 1)
        self.label_32 = QtGui.QLabel(self.widget)
        self.label_32.setText(_fromUtf8(""))
        self.label_32.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 3, 4, 1, 1)
        self.label_35 = QtGui.QLabel(self.widget)
        self.label_35.setText(_fromUtf8(""))
        self.label_35.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 1, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_75 = QtGui.QLabel(self.widget)
        self.label_75.setText(_fromUtf8(""))
        self.label_75.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_75.setScaledContents(True)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout.addWidget(self.label_75, 1, 10, 1, 1)
        self.label_30 = QtGui.QLabel(self.widget)
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 2, 4, 1, 1)
        self.label_67 = QtGui.QLabel(self.widget)
        self.label_67.setText(_fromUtf8(""))
        self.label_67.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_67.setScaledContents(True)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout.addWidget(self.label_67, 1, 9, 1, 1)
        self.label_86 = QtGui.QLabel(self.widget)
        self.label_86.setText(_fromUtf8(""))
        self.label_86.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_86.setScaledContents(True)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout.addWidget(self.label_86, 2, 11, 1, 1)
        self.label_112 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_112.setFont(font)
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.gridLayout.addWidget(self.label_112, 3, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.widget)
        self.label_48.setText(_fromUtf8(""))
        self.label_48.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout.addWidget(self.label_48, 3, 6, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.label_91 = QtGui.QLabel(self.widget)
        self.label_91.setText(_fromUtf8(""))
        self.label_91.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_91.setScaledContents(True)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout.addWidget(self.label_91, 3, 12, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 5, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.widget)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 5, 3, 1, 1)
        self.label_29 = QtGui.QLabel(self.widget)
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 5, 4, 1, 1)
        self.label_52 = QtGui.QLabel(self.widget)
        self.label_52.setText(_fromUtf8(""))
        self.label_52.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_52.setScaledContents(True)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout.addWidget(self.label_52, 4, 7, 1, 1)
        self.label_37 = QtGui.QLabel(self.widget)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 5, 5, 1, 1)
        self.label_88 = QtGui.QLabel(self.widget)
        self.label_88.setText(_fromUtf8(""))
        self.label_88.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_88.setScaledContents(True)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout.addWidget(self.label_88, 3, 11, 1, 1)
        self.label_45 = QtGui.QLabel(self.widget)
        self.label_45.setText(_fromUtf8(""))
        self.label_45.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 5, 6, 1, 1)
        self.label_113 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_113.setFont(font)
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.gridLayout.addWidget(self.label_113, 4, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.widget)
        self.label_28.setText(_fromUtf8(""))
        self.label_28.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 4, 4, 1, 1)
        self.label_85 = QtGui.QLabel(self.widget)
        self.label_85.setText(_fromUtf8(""))
        self.label_85.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_85.setScaledContents(True)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout.addWidget(self.label_85, 5, 11, 1, 1)
        self.label_77 = QtGui.QLabel(self.widget)
        self.label_77.setText(_fromUtf8(""))
        self.label_77.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_77.setScaledContents(True)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout.addWidget(self.label_77, 5, 10, 1, 1)
        self.label_89 = QtGui.QLabel(self.widget)
        self.label_89.setText(_fromUtf8(""))
        self.label_89.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_89.setScaledContents(True)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout.addWidget(self.label_89, 5, 12, 1, 1)
        self.label_84 = QtGui.QLabel(self.widget)
        self.label_84.setText(_fromUtf8(""))
        self.label_84.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_84.setScaledContents(True)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout.addWidget(self.label_84, 4, 11, 1, 1)
        self.label_115 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_115.setFont(font)
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.gridLayout.addWidget(self.label_115, 6, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 6, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.widget)
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 4, 3, 1, 1)
        self.label_53 = QtGui.QLabel(self.widget)
        self.label_53.setText(_fromUtf8(""))
        self.label_53.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_53.setScaledContents(True)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout.addWidget(self.label_53, 5, 7, 1, 1)
        self.label_61 = QtGui.QLabel(self.widget)
        self.label_61.setText(_fromUtf8(""))
        self.label_61.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_61.setScaledContents(True)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout.addWidget(self.label_61, 5, 8, 1, 1)
        self.label_69 = QtGui.QLabel(self.widget)
        self.label_69.setText(_fromUtf8(""))
        self.label_69.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_69.setScaledContents(True)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout.addWidget(self.label_69, 5, 9, 1, 1)
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 6, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_60 = QtGui.QLabel(self.widget)
        self.label_60.setText(_fromUtf8(""))
        self.label_60.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout.addWidget(self.label_60, 4, 8, 1, 1)
        self.label_44 = QtGui.QLabel(self.widget)
        self.label_44.setText(_fromUtf8(""))
        self.label_44.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 4, 6, 1, 1)
        self.label_68 = QtGui.QLabel(self.widget)
        self.label_68.setText(_fromUtf8(""))
        self.label_68.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_68.setScaledContents(True)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout.addWidget(self.label_68, 4, 9, 1, 1)
        self.label_36 = QtGui.QLabel(self.widget)
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 4, 5, 1, 1)
        self.label_76 = QtGui.QLabel(self.widget)
        self.label_76.setText(_fromUtf8(""))
        self.label_76.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_76.setScaledContents(True)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout.addWidget(self.label_76, 4, 10, 1, 1)
        self.label_92 = QtGui.QLabel(self.widget)
        self.label_92.setText(_fromUtf8(""))
        self.label_92.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_92.setScaledContents(True)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout.addWidget(self.label_92, 4, 12, 1, 1)
        self.label_114 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_114.setFont(font)
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.gridLayout.addWidget(self.label_114, 5, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.widget)
        self.label_33.setText(_fromUtf8(""))
        self.label_33.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.label_33, 6, 5, 1, 1)
        self.label_73 = QtGui.QLabel(self.widget)
        self.label_73.setText(_fromUtf8(""))
        self.label_73.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_73.setScaledContents(True)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout.addWidget(self.label_73, 6, 10, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 1, 1, 1)
        self.label_74 = QtGui.QLabel(self.widget)
        self.label_74.setText(_fromUtf8(""))
        self.label_74.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_74.setScaledContents(True)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout.addWidget(self.label_74, 7, 10, 1, 1)
        self.label_25 = QtGui.QLabel(self.widget)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 6, 4, 1, 1)
        self.label_81 = QtGui.QLabel(self.widget)
        self.label_81.setText(_fromUtf8(""))
        self.label_81.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_81.setScaledContents(True)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout.addWidget(self.label_81, 6, 11, 1, 1)
        self.label_49 = QtGui.QLabel(self.widget)
        self.label_49.setText(_fromUtf8(""))
        self.label_49.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout.addWidget(self.label_49, 6, 7, 1, 1)
        self.label_41 = QtGui.QLabel(self.widget)
        self.label_41.setText(_fromUtf8(""))
        self.label_41.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 6, 6, 1, 1)
        self.label_95 = QtGui.QLabel(self.widget)
        self.label_95.setText(_fromUtf8(""))
        self.label_95.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_95.setScaledContents(True)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout.addWidget(self.label_95, 6, 12, 1, 1)
        self.label_42 = QtGui.QLabel(self.widget)
        self.label_42.setText(_fromUtf8(""))
        self.label_42.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout.addWidget(self.label_42, 7, 6, 1, 1)
        self.label_57 = QtGui.QLabel(self.widget)
        self.label_57.setText(_fromUtf8(""))
        self.label_57.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout.addWidget(self.label_57, 6, 8, 1, 1)
        self.label_18 = QtGui.QLabel(self.widget)
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 7, 3, 1, 1)
        self.label_94 = QtGui.QLabel(self.widget)
        self.label_94.setText(_fromUtf8(""))
        self.label_94.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_94.setScaledContents(True)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.gridLayout.addWidget(self.label_94, 7, 12, 1, 1)
        self.label_82 = QtGui.QLabel(self.widget)
        self.label_82.setText(_fromUtf8(""))
        self.label_82.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_82.setScaledContents(True)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout.addWidget(self.label_82, 7, 11, 1, 1)
        self.label_117 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_117.setFont(font)
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.gridLayout.addWidget(self.label_117, 8, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 1, 1, 1)
        self.label_116 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_116.setFont(font)
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.gridLayout.addWidget(self.label_116, 7, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.widget)
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 8, 3, 1, 1)
        self.label_66 = QtGui.QLabel(self.widget)
        self.label_66.setText(_fromUtf8(""))
        self.label_66.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_66.setScaledContents(True)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout.addWidget(self.label_66, 7, 9, 1, 1)
        self.label_31 = QtGui.QLabel(self.widget)
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 8, 4, 1, 1)
        self.label_39 = QtGui.QLabel(self.widget)
        self.label_39.setText(_fromUtf8(""))
        self.label_39.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 8, 5, 1, 1)
        self.label_50 = QtGui.QLabel(self.widget)
        self.label_50.setText(_fromUtf8(""))
        self.label_50.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout.addWidget(self.label_50, 7, 7, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 7, 2, 1, 1)
        self.label_58 = QtGui.QLabel(self.widget)
        self.label_58.setText(_fromUtf8(""))
        self.label_58.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout.addWidget(self.label_58, 7, 8, 1, 1)
        self.label_47 = QtGui.QLabel(self.widget)
        self.label_47.setText(_fromUtf8(""))
        self.label_47.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout.addWidget(self.label_47, 8, 6, 1, 1)
        self.label_63 = QtGui.QLabel(self.widget)
        self.label_63.setText(_fromUtf8(""))
        self.label_63.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_63.setScaledContents(True)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout.addWidget(self.label_63, 8, 8, 1, 1)
        self.label_65 = QtGui.QLabel(self.widget)
        self.label_65.setText(_fromUtf8(""))
        self.label_65.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_65.setScaledContents(True)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout.addWidget(self.label_65, 6, 9, 1, 1)
        self.label_26 = QtGui.QLabel(self.widget)
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 7, 4, 1, 1)
        self.label_34 = QtGui.QLabel(self.widget)
        self.label_34.setText(_fromUtf8(""))
        self.label_34.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 7, 5, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 8, 2, 1, 1)
        self.label_55 = QtGui.QLabel(self.widget)
        self.label_55.setText(_fromUtf8(""))
        self.label_55.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout.addWidget(self.label_55, 8, 7, 1, 1)
        self.label_71 = QtGui.QLabel(self.widget)
        self.label_71.setText(_fromUtf8(""))
        self.label_71.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_71.setScaledContents(True)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout.addWidget(self.label_71, 8, 9, 1, 1)
        self.label_87 = QtGui.QLabel(self.widget)
        self.label_87.setText(_fromUtf8(""))
        self.label_87.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_87.setScaledContents(True)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout.addWidget(self.label_87, 8, 11, 1, 1)
        self.label_79 = QtGui.QLabel(self.widget)
        self.label_79.setText(_fromUtf8(""))
        self.label_79.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_79.setScaledContents(True)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout.addWidget(self.label_79, 8, 10, 1, 1)
        self.label_96 = QtGui.QLabel(self.widget)
        self.label_96.setText(_fromUtf8(""))
        self.label_96.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout.addWidget(self.label_96, 8, 12, 1, 1)
        self.label_97 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_97.setFont(font)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.gridLayout.addWidget(self.label_97, 0, 1, 1, 1)
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.label_46.raise_()
        self.label_47.raise_()
        self.label_48.raise_()
        self.label_49.raise_()
        self.label_50.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.label_65.raise_()
        self.label_66.raise_()
        self.label_67.raise_()
        self.label_68.raise_()
        self.label_69.raise_()
        self.label_70.raise_()
        self.label_71.raise_()
        self.label_72.raise_()
        self.label_73.raise_()
        self.label_74.raise_()
        self.label_75.raise_()
        self.label_76.raise_()
        self.label_77.raise_()
        self.label_78.raise_()
        self.label_79.raise_()
        self.label_80.raise_()
        self.label_81.raise_()
        self.label_82.raise_()
        self.label_83.raise_()
        self.label_84.raise_()
        self.label_85.raise_()
        self.label_86.raise_()
        self.label_87.raise_()
        self.label_88.raise_()
        self.label_89.raise_()
        self.label_90.raise_()
        self.label_91.raise_()
        self.label_92.raise_()
        self.label_93.raise_()
        self.label_94.raise_()
        self.label_95.raise_()
        self.label_96.raise_()
        self.label_97.raise_()
        self.label_98.raise_()
        self.label_99.raise_()
        self.label_100.raise_()
        self.label_101.raise_()
        self.label_102.raise_()
        self.label_103.raise_()
        self.label_104.raise_()
        self.label_105.raise_()
        self.label_106.raise_()
        self.label_107.raise_()
        self.label_108.raise_()
        self.label_109.raise_()
        self.label_110.raise_()
        self.label_111.raise_()
        self.label_112.raise_()
        self.label_113.raise_()
        self.label_114.raise_()
        self.label_115.raise_()
        self.label_116.raise_()
        self.label_117.raise_()
        self.label_109.raise_()
        self.pushButton.raise_()
        self.label_118.raise_()
        self.label_119.raise_()

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton.setText(_translate("Form", "NEXT", None))
        self.label_118.setText(_translate("Form", "Click & Drag ", None))
        self.label_119.setText(_translate("Form", "to select wells", None))
        self.label_107.setText(_translate("Form", "11", None))
        self.label_110.setText(_translate("Form", "A", None))
        self.label_98.setText(_translate("Form", "2", None))
        self.label_99.setText(_translate("Form", "3", None))
        self.label_100.setText(_translate("Form", "4", None))
        self.label_103.setText(_translate("Form", "7", None))
        self.label_106.setText(_translate("Form", "10", None))
        self.label_101.setText(_translate("Form", "5", None))
        self.label_108.setText(_translate("Form", "12", None))
        self.label_105.setText(_translate("Form", "9", None))
        self.label_102.setText(_translate("Form", "6", None))
        self.label_104.setText(_translate("Form", "8", None))
        self.label_111.setText(_translate("Form", "B", None))
        self.label_112.setText(_translate("Form", "C", None))
        self.label_113.setText(_translate("Form", "D", None))
        self.label_115.setText(_translate("Form", "F", None))
        self.label_114.setText(_translate("Form", "E", None))
        self.label_117.setText(_translate("Form", "H", None))
        self.label_116.setText(_translate("Form", "G", None))
        self.label_97.setText(_translate("Form", "1", None))

def main():
    import sys
    app = QtGui.QApplication(sys.argv)
    app.setStyle("Plastique")
    ex = Ui_Form()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()