# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'wellSelectScreen.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class wellSelectScreen(QtGui.QWidget):
    def __init__(self):
        super(wellSelectScreen, self).__init__()
        self.initUI()
        self.clearButton.clicked.connect(self.clearWells)
        #self.show()

    def initUI(self):
        self.setObjectName(_fromUtf8("self"))
        self.resize(794, 430)
        self.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);"))
        self.nextButton = QtGui.QPushButton(self)
        self.nextButton.setGeometry(QtCore.QRect(610, 340, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nextButton.setFont(font)
        self.nextButton.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 127);"))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.label_118 = QtGui.QLabel(self)
        self.label_118.setGeometry(QtCore.QRect(620, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_118.setFont(font)
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.label_119 = QtGui.QLabel(self)
        self.label_119.setGeometry(QtCore.QRect(610, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_119.setFont(font)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.clearButton = QtGui.QPushButton(self)
        self.clearButton.setGeometry(QtCore.QRect(610, 270, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 57, 43);"))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.widget = QtGui.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(20, 20, 551, 381))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_107 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_107.setFont(font)
        self.label_107.setAlignment(QtCore.Qt.AlignCenter)
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout.addWidget(self.label_107, 0, 11, 1, 1)
        self.label_110 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_110.setFont(font)
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.gridLayout.addWidget(self.label_110, 1, 0, 1, 1)
        self.label_98 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_98.setFont(font)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout.addWidget(self.label_98, 0, 2, 1, 1)
        self.label_99 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_99.setFont(font)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout.addWidget(self.label_99, 0, 3, 1, 1)
        self.A1 = QtGui.QLabel(self.widget)
        self.A1.setText(_fromUtf8(""))
        self.A1.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A1.setScaledContents(True)
        self.A1.setObjectName(_fromUtf8("A1"))
        self.gridLayout.addWidget(self.A1, 1, 1, 1, 1)
        self.label_100 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_100.setFont(font)
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout.addWidget(self.label_100, 0, 4, 1, 1)
        self.label_103 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_103.setFont(font)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout.addWidget(self.label_103, 0, 7, 1, 1)
        self.label_106 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_106.setFont(font)
        self.label_106.setAlignment(QtCore.Qt.AlignCenter)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout.addWidget(self.label_106, 0, 10, 1, 1)
        self.A2 = QtGui.QLabel(self.widget)
        self.A2.setText(_fromUtf8(""))
        self.A2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A2.setScaledContents(True)
        self.A2.setObjectName(_fromUtf8("A2"))
        self.gridLayout.addWidget(self.A2, 1, 2, 1, 1)
        self.label_101 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_101.setFont(font)
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout.addWidget(self.label_101, 0, 5, 1, 1)
        self.label_108 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_108.setFont(font)
        self.label_108.setAlignment(QtCore.Qt.AlignCenter)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout.addWidget(self.label_108, 0, 12, 1, 1)
        self.A3 = QtGui.QLabel(self.widget)
        self.A3.setText(_fromUtf8(""))
        self.A3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A3.setScaledContents(True)
        self.A3.setObjectName(_fromUtf8("A3"))
        self.gridLayout.addWidget(self.A3, 1, 3, 1, 1)
        self.label_109 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_109.setFont(font)
        self.label_109.setText(_fromUtf8(""))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.gridLayout.addWidget(self.label_109, 0, 0, 1, 1)
        self.A4 = QtGui.QLabel(self.widget)
        self.A4.setText(_fromUtf8(""))
        self.A4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A4.setScaledContents(True)
        self.A4.setObjectName(_fromUtf8("A4"))
        self.gridLayout.addWidget(self.A4, 1, 4, 1, 1)
        self.label_105 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_105.setFont(font)
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout.addWidget(self.label_105, 0, 9, 1, 1)
        self.label_102 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_102.setFont(font)
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout.addWidget(self.label_102, 0, 6, 1, 1)
        self.label_104 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_104.setFont(font)
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout.addWidget(self.label_104, 0, 8, 1, 1)
        self.B6 = QtGui.QLabel(self.widget)
        self.B6.setText(_fromUtf8(""))
        self.B6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B6.setScaledContents(True)
        self.B6.setObjectName(_fromUtf8("B6"))
        self.gridLayout.addWidget(self.B6, 2, 6, 1, 1)
        self.A11 = QtGui.QLabel(self.widget)
        self.A11.setText(_fromUtf8(""))
        self.A11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A11.setScaledContents(True)
        self.A11.setObjectName(_fromUtf8("A11"))
        self.gridLayout.addWidget(self.A11, 1, 11, 1, 1)
        self.A6 = QtGui.QLabel(self.widget)
        self.A6.setText(_fromUtf8(""))
        self.A6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A6.setScaledContents(True)
        self.A6.setObjectName(_fromUtf8("A6"))
        self.gridLayout.addWidget(self.A6, 1, 6, 1, 1)
        self.B3 = QtGui.QLabel(self.widget)
        self.B3.setText(_fromUtf8(""))
        self.B3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B3.setScaledContents(True)
        self.B3.setObjectName(_fromUtf8("B3"))
        self.gridLayout.addWidget(self.B3, 2, 3, 1, 1)
        self.B8 = QtGui.QLabel(self.widget)
        self.B8.setText(_fromUtf8(""))
        self.B8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B8.setScaledContents(True)
        self.B8.setObjectName(_fromUtf8("B8"))
        self.gridLayout.addWidget(self.B8, 2, 8, 1, 1)
        self.A12 = QtGui.QLabel(self.widget)
        self.A12.setText(_fromUtf8(""))
        self.A12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A12.setScaledContents(True)
        self.A12.setObjectName(_fromUtf8("A12"))
        self.gridLayout.addWidget(self.A12, 1, 12, 1, 1)
        self.C1 = QtGui.QLabel(self.widget)
        self.C1.setText(_fromUtf8(""))
        self.C1.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C1.setScaledContents(True)
        self.C1.setObjectName(_fromUtf8("C1"))
        self.gridLayout.addWidget(self.C1, 3, 1, 1, 1)
        self.B1 = QtGui.QLabel(self.widget)
        self.B1.setText(_fromUtf8(""))
        self.B1.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B1.setScaledContents(True)
        self.B1.setObjectName(_fromUtf8("B1"))
        self.gridLayout.addWidget(self.B1, 2, 1, 1, 1)
        self.C7 = QtGui.QLabel(self.widget)
        self.C7.setText(_fromUtf8(""))
        self.C7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C7.setScaledContents(True)
        self.C7.setObjectName(_fromUtf8("C7"))
        self.gridLayout.addWidget(self.C7, 3, 7, 1, 1)
        self.C8 = QtGui.QLabel(self.widget)
        self.C8.setText(_fromUtf8(""))
        self.C8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C8.setScaledContents(True)
        self.C8.setObjectName(_fromUtf8("C8"))
        self.gridLayout.addWidget(self.C8, 3, 8, 1, 1)
        self.A8 = QtGui.QLabel(self.widget)
        self.A8.setText(_fromUtf8(""))
        self.A8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A8.setScaledContents(True)
        self.A8.setObjectName(_fromUtf8("A8"))
        self.gridLayout.addWidget(self.A8, 1, 8, 1, 1)
        self.label_111 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_111.setFont(font)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout.addWidget(self.label_111, 2, 0, 1, 1)
        self.B10 = QtGui.QLabel(self.widget)
        self.B10.setText(_fromUtf8(""))
        self.B10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B10.setScaledContents(True)
        self.B10.setObjectName(_fromUtf8("B10"))
        self.gridLayout.addWidget(self.B10, 2, 10, 1, 1)
        self.C3 = QtGui.QLabel(self.widget)
        self.C3.setText(_fromUtf8(""))
        self.C3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C3.setScaledContents(True)
        self.C3.setObjectName(_fromUtf8("C3"))
        self.gridLayout.addWidget(self.C3, 3, 3, 1, 1)
        self.C5 = QtGui.QLabel(self.widget)
        self.C5.setText(_fromUtf8(""))
        self.C5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C5.setScaledContents(True)
        self.C5.setObjectName(_fromUtf8("C5"))
        self.gridLayout.addWidget(self.C5, 3, 5, 1, 1)
        self.C9 = QtGui.QLabel(self.widget)
        self.C9.setText(_fromUtf8(""))
        self.C9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C9.setScaledContents(True)
        self.C9.setObjectName(_fromUtf8("C9"))
        self.gridLayout.addWidget(self.C9, 3, 9, 1, 1)
        self.C10 = QtGui.QLabel(self.widget)
        self.C10.setText(_fromUtf8(""))
        self.C10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C10.setScaledContents(True)
        self.C10.setObjectName(_fromUtf8("C10"))
        self.gridLayout.addWidget(self.C10, 3, 10, 1, 1)
        self.B7 = QtGui.QLabel(self.widget)
        self.B7.setText(_fromUtf8(""))
        self.B7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B7.setScaledContents(True)
        self.B7.setObjectName(_fromUtf8("B7"))
        self.gridLayout.addWidget(self.B7, 2, 7, 1, 1)
        self.B5 = QtGui.QLabel(self.widget)
        self.B5.setText(_fromUtf8(""))
        self.B5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B5.setScaledContents(True)
        self.B5.setObjectName(_fromUtf8("B5"))
        self.gridLayout.addWidget(self.B5, 2, 5, 1, 1)
        self.A7 = QtGui.QLabel(self.widget)
        self.A7.setText(_fromUtf8(""))
        self.A7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A7.setScaledContents(True)
        self.A7.setObjectName(_fromUtf8("A7"))
        self.gridLayout.addWidget(self.A7, 1, 7, 1, 1)
        self.B12 = QtGui.QLabel(self.widget)
        self.B12.setText(_fromUtf8(""))
        self.B12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B12.setScaledContents(True)
        self.B12.setObjectName(_fromUtf8("B12"))
        self.gridLayout.addWidget(self.B12, 2, 12, 1, 1)
        self.C2 = QtGui.QLabel(self.widget)
        self.C2.setText(_fromUtf8(""))
        self.C2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C2.setScaledContents(True)
        self.C2.setObjectName(_fromUtf8("C2"))
        self.gridLayout.addWidget(self.C2, 3, 2, 1, 1)
        self.B9 = QtGui.QLabel(self.widget)
        self.B9.setText(_fromUtf8(""))
        self.B9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B9.setScaledContents(True)
        self.B9.setObjectName(_fromUtf8("B9"))
        self.gridLayout.addWidget(self.B9, 2, 9, 1, 1)
        self.C4 = QtGui.QLabel(self.widget)
        self.C4.setText(_fromUtf8(""))
        self.C4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C4.setScaledContents(True)
        self.C4.setObjectName(_fromUtf8("C4"))
        self.gridLayout.addWidget(self.C4, 3, 4, 1, 1)
        self.A5 = QtGui.QLabel(self.widget)
        self.A5.setText(_fromUtf8(""))
        self.A5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A5.setScaledContents(True)
        self.A5.setObjectName(_fromUtf8("A5"))
        self.gridLayout.addWidget(self.A5, 1, 5, 1, 1)
        self.B2 = QtGui.QLabel(self.widget)
        self.B2.setText(_fromUtf8(""))
        self.B2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B2.setScaledContents(True)
        self.B2.setObjectName(_fromUtf8("B2"))
        self.gridLayout.addWidget(self.B2, 2, 2, 1, 1)
        self.A10 = QtGui.QLabel(self.widget)
        self.A10.setText(_fromUtf8(""))
        self.A10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A10.setScaledContents(True)
        self.A10.setObjectName(_fromUtf8("A10"))
        self.gridLayout.addWidget(self.A10, 1, 10, 1, 1)
        self.B4 = QtGui.QLabel(self.widget)
        self.B4.setText(_fromUtf8(""))
        self.B4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B4.setScaledContents(True)
        self.B4.setObjectName(_fromUtf8("B4"))
        self.gridLayout.addWidget(self.B4, 2, 4, 1, 1)
        self.A9 = QtGui.QLabel(self.widget)
        self.A9.setText(_fromUtf8(""))
        self.A9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.A9.setScaledContents(True)
        self.A9.setObjectName(_fromUtf8("A9"))
        self.gridLayout.addWidget(self.A9, 1, 9, 1, 1)
        self.B11 = QtGui.QLabel(self.widget)
        self.B11.setText(_fromUtf8(""))
        self.B11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.B11.setScaledContents(True)
        self.B11.setObjectName(_fromUtf8("B11"))
        self.gridLayout.addWidget(self.B11, 2, 11, 1, 1)
        self.label_112 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_112.setFont(font)
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.gridLayout.addWidget(self.label_112, 3, 0, 1, 1)
        self.C6 = QtGui.QLabel(self.widget)
        self.C6.setText(_fromUtf8(""))
        self.C6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C6.setScaledContents(True)
        self.C6.setObjectName(_fromUtf8("C6"))
        self.gridLayout.addWidget(self.C6, 3, 6, 1, 1)
        self.E1 = QtGui.QLabel(self.widget)
        self.E1.setText(_fromUtf8(""))
        self.E1.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E1.setScaledContents(True)
        self.E1.setObjectName(_fromUtf8("E1"))
        self.gridLayout.addWidget(self.E1, 5, 1, 1, 1)
        self.C12 = QtGui.QLabel(self.widget)
        self.C12.setText(_fromUtf8(""))
        self.C12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C12.setScaledContents(True)
        self.C12.setObjectName(_fromUtf8("C12"))
        self.gridLayout.addWidget(self.C12, 3, 12, 1, 1)
        self.D2 = QtGui.QLabel(self.widget)
        self.D2.setText(_fromUtf8(""))
        self.D2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D2.setScaledContents(True)
        self.D2.setObjectName(_fromUtf8("D2"))
        self.gridLayout.addWidget(self.D2, 4, 2, 1, 1)
        self.E2 = QtGui.QLabel(self.widget)
        self.E2.setText(_fromUtf8(""))
        self.E2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E2.setScaledContents(True)
        self.E2.setObjectName(_fromUtf8("E2"))
        self.gridLayout.addWidget(self.E2, 5, 2, 1, 1)
        self.E3 = QtGui.QLabel(self.widget)
        self.E3.setText(_fromUtf8(""))
        self.E3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E3.setScaledContents(True)
        self.E3.setObjectName(_fromUtf8("E3"))
        self.gridLayout.addWidget(self.E3, 5, 3, 1, 1)
        self.E4 = QtGui.QLabel(self.widget)
        self.E4.setText(_fromUtf8(""))
        self.E4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E4.setScaledContents(True)
        self.E4.setObjectName(_fromUtf8("E4"))
        self.gridLayout.addWidget(self.E4, 5, 4, 1, 1)
        self.D7 = QtGui.QLabel(self.widget)
        self.D7.setText(_fromUtf8(""))
        self.D7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D7.setScaledContents(True)
        self.D7.setObjectName(_fromUtf8("D7"))
        self.gridLayout.addWidget(self.D7, 4, 7, 1, 1)
        self.E5 = QtGui.QLabel(self.widget)
        self.E5.setText(_fromUtf8(""))
        self.E5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E5.setScaledContents(True)
        self.E5.setObjectName(_fromUtf8("E5"))
        self.gridLayout.addWidget(self.E5, 5, 5, 1, 1)
        self.C11 = QtGui.QLabel(self.widget)
        self.C11.setText(_fromUtf8(""))
        self.C11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.C11.setScaledContents(True)
        self.C11.setObjectName(_fromUtf8("C11"))
        self.gridLayout.addWidget(self.C11, 3, 11, 1, 1)
        self.E6 = QtGui.QLabel(self.widget)
        self.E6.setText(_fromUtf8(""))
        self.E6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E6.setScaledContents(True)
        self.E6.setObjectName(_fromUtf8("E6"))
        self.gridLayout.addWidget(self.E6, 5, 6, 1, 1)
        self.label_113 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_113.setFont(font)
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.gridLayout.addWidget(self.label_113, 4, 0, 1, 1)
        self.D4 = QtGui.QLabel(self.widget)
        self.D4.setText(_fromUtf8(""))
        self.D4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D4.setScaledContents(True)
        self.D4.setObjectName(_fromUtf8("D4"))
        self.gridLayout.addWidget(self.D4, 4, 4, 1, 1)
        self.E11 = QtGui.QLabel(self.widget)
        self.E11.setText(_fromUtf8(""))
        self.E11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E11.setScaledContents(True)
        self.E11.setObjectName(_fromUtf8("E11"))
        self.gridLayout.addWidget(self.E11, 5, 11, 1, 1)
        self.E10 = QtGui.QLabel(self.widget)
        self.E10.setText(_fromUtf8(""))
        self.E10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E10.setScaledContents(True)
        self.E10.setObjectName(_fromUtf8("E10"))
        self.gridLayout.addWidget(self.E10, 5, 10, 1, 1)
        self.E12 = QtGui.QLabel(self.widget)
        self.E12.setText(_fromUtf8(""))
        self.E12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E12.setScaledContents(True)
        self.E12.setObjectName(_fromUtf8("E12"))
        self.gridLayout.addWidget(self.E12, 5, 12, 1, 1)
        self.D11 = QtGui.QLabel(self.widget)
        self.D11.setText(_fromUtf8(""))
        self.D11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D11.setScaledContents(True)
        self.D11.setObjectName(_fromUtf8("D11"))
        self.gridLayout.addWidget(self.D11, 4, 11, 1, 1)
        self.label_115 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_115.setFont(font)
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.gridLayout.addWidget(self.label_115, 6, 0, 1, 1)
        self.F1 = QtGui.QLabel(self.widget)
        self.F1.setText(_fromUtf8(""))
        self.F1.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F1.setScaledContents(True)
        self.F1.setObjectName(_fromUtf8("F1"))
        self.gridLayout.addWidget(self.F1, 6, 1, 1, 1)
        self.F2 = QtGui.QLabel(self.widget)
        self.F2.setText(_fromUtf8(""))
        self.F2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F2.setScaledContents(True)
        self.F2.setObjectName(_fromUtf8("F2"))
        self.gridLayout.addWidget(self.F2, 6, 2, 1, 1)
        self.D3 = QtGui.QLabel(self.widget)
        self.D3.setText(_fromUtf8(""))
        self.D3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D3.setScaledContents(True)
        self.D3.setObjectName(_fromUtf8("D3"))
        self.gridLayout.addWidget(self.D3, 4, 3, 1, 1)
        self.E7 = QtGui.QLabel(self.widget)
        self.E7.setText(_fromUtf8(""))
        self.E7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E7.setScaledContents(True)
        self.E7.setObjectName(_fromUtf8("E7"))
        self.gridLayout.addWidget(self.E7, 5, 7, 1, 1)
        self.E8 = QtGui.QLabel(self.widget)
        self.E8.setText(_fromUtf8(""))
        self.E8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E8.setScaledContents(True)
        self.E8.setObjectName(_fromUtf8("E8"))
        self.gridLayout.addWidget(self.E8, 5, 8, 1, 1)
        self.E9 = QtGui.QLabel(self.widget)
        self.E9.setText(_fromUtf8(""))
        self.E9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.E9.setScaledContents(True)
        self.E9.setObjectName(_fromUtf8("E9"))
        self.gridLayout.addWidget(self.E9, 5, 9, 1, 1)
        self.F3 = QtGui.QLabel(self.widget)
        self.F3.setText(_fromUtf8(""))
        self.F3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F3.setScaledContents(True)
        self.F3.setObjectName(_fromUtf8("F3"))
        self.gridLayout.addWidget(self.F3, 6, 3, 1, 1)
        self.D1 = QtGui.QLabel(self.widget)
        self.D1.setText(_fromUtf8(""))
        self.D1.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D1.setScaledContents(True)
        self.D1.setObjectName(_fromUtf8("D1"))
        self.gridLayout.addWidget(self.D1, 4, 1, 1, 1)
        self.D8 = QtGui.QLabel(self.widget)
        self.D8.setText(_fromUtf8(""))
        self.D8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D8.setScaledContents(True)
        self.D8.setObjectName(_fromUtf8("D8"))
        self.gridLayout.addWidget(self.D8, 4, 8, 1, 1)
        self.D6 = QtGui.QLabel(self.widget)
        self.D6.setText(_fromUtf8(""))
        self.D6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D6.setScaledContents(True)
        self.D6.setObjectName(_fromUtf8("D6"))
        self.gridLayout.addWidget(self.D6, 4, 6, 1, 1)
        self.D9 = QtGui.QLabel(self.widget)
        self.D9.setText(_fromUtf8(""))
        self.D9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D9.setScaledContents(True)
        self.D9.setObjectName(_fromUtf8("D9"))
        self.gridLayout.addWidget(self.D9, 4, 9, 1, 1)
        self.D5 = QtGui.QLabel(self.widget)
        self.D5.setText(_fromUtf8(""))
        self.D5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D5.setScaledContents(True)
        self.D5.setObjectName(_fromUtf8("D5"))
        self.gridLayout.addWidget(self.D5, 4, 5, 1, 1)
        self.D10 = QtGui.QLabel(self.widget)
        self.D10.setText(_fromUtf8(""))
        self.D10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D10.setScaledContents(True)
        self.D10.setObjectName(_fromUtf8("D10"))
        self.gridLayout.addWidget(self.D10, 4, 10, 1, 1)
        self.D12 = QtGui.QLabel(self.widget)
        self.D12.setText(_fromUtf8(""))
        self.D12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.D12.setScaledContents(True)
        self.D12.setObjectName(_fromUtf8("D12"))
        self.gridLayout.addWidget(self.D12, 4, 12, 1, 1)
        self.label_114 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_114.setFont(font)
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.gridLayout.addWidget(self.label_114, 5, 0, 1, 1)
        self.F5 = QtGui.QLabel(self.widget)
        self.F5.setText(_fromUtf8(""))
        self.F5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F5.setScaledContents(True)
        self.F5.setObjectName(_fromUtf8("F5"))
        self.gridLayout.addWidget(self.F5, 6, 5, 1, 1)
        self.F10 = QtGui.QLabel(self.widget)
        self.F10.setText(_fromUtf8(""))
        self.F10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F10.setScaledContents(True)
        self.F10.setObjectName(_fromUtf8("F10"))
        self.gridLayout.addWidget(self.F10, 6, 10, 1, 1)
        self.G1 = QtGui.QLabel(self.widget)
        self.G1.setText(_fromUtf8(""))
        self.G1.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G1.setScaledContents(True)
        self.G1.setObjectName(_fromUtf8("G1"))
        self.gridLayout.addWidget(self.G1, 7, 1, 1, 1)
        self.G10 = QtGui.QLabel(self.widget)
        self.G10.setText(_fromUtf8(""))
        self.G10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G10.setScaledContents(True)
        self.G10.setObjectName(_fromUtf8("G10"))
        self.gridLayout.addWidget(self.G10, 7, 10, 1, 1)
        self.F4 = QtGui.QLabel(self.widget)
        self.F4.setText(_fromUtf8(""))
        self.F4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F4.setScaledContents(True)
        self.F4.setObjectName(_fromUtf8("F4"))
        self.gridLayout.addWidget(self.F4, 6, 4, 1, 1)
        self.F11 = QtGui.QLabel(self.widget)
        self.F11.setText(_fromUtf8(""))
        self.F11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F11.setScaledContents(True)
        self.F11.setObjectName(_fromUtf8("F11"))
        self.gridLayout.addWidget(self.F11, 6, 11, 1, 1)
        self.F7 = QtGui.QLabel(self.widget)
        self.F7.setText(_fromUtf8(""))
        self.F7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F7.setScaledContents(True)
        self.F7.setObjectName(_fromUtf8("F7"))
        self.gridLayout.addWidget(self.F7, 6, 7, 1, 1)
        self.F6 = QtGui.QLabel(self.widget)
        self.F6.setText(_fromUtf8(""))
        self.F6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F6.setScaledContents(True)
        self.F6.setObjectName(_fromUtf8("F6"))
        self.gridLayout.addWidget(self.F6, 6, 6, 1, 1)
        self.F12 = QtGui.QLabel(self.widget)
        self.F12.setText(_fromUtf8(""))
        self.F12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F12.setScaledContents(True)
        self.F12.setObjectName(_fromUtf8("F12"))
        self.gridLayout.addWidget(self.F12, 6, 12, 1, 1)
        self.G6 = QtGui.QLabel(self.widget)
        self.G6.setText(_fromUtf8(""))
        self.G6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G6.setScaledContents(True)
        self.G6.setObjectName(_fromUtf8("G6"))
        self.gridLayout.addWidget(self.G6, 7, 6, 1, 1)
        self.F8 = QtGui.QLabel(self.widget)
        self.F8.setText(_fromUtf8(""))
        self.F8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F8.setScaledContents(True)
        self.F8.setObjectName(_fromUtf8("F8"))
        self.gridLayout.addWidget(self.F8, 6, 8, 1, 1)
        self.G3 = QtGui.QLabel(self.widget)
        self.G3.setText(_fromUtf8(""))
        self.G3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G3.setScaledContents(True)
        self.G3.setObjectName(_fromUtf8("G3"))
        self.gridLayout.addWidget(self.G3, 7, 3, 1, 1)
        self.G12 = QtGui.QLabel(self.widget)
        self.G12.setText(_fromUtf8(""))
        self.G12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G12.setScaledContents(True)
        self.G12.setObjectName(_fromUtf8("G12"))
        self.gridLayout.addWidget(self.G12, 7, 12, 1, 1)
        self.G11 = QtGui.QLabel(self.widget)
        self.G11.setText(_fromUtf8(""))
        self.G11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G11.setScaledContents(True)
        self.G11.setObjectName(_fromUtf8("G11"))
        self.gridLayout.addWidget(self.G11, 7, 11, 1, 1)
        self.label_117 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_117.setFont(font)
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.gridLayout.addWidget(self.label_117, 8, 0, 1, 1)
        self.H1 = QtGui.QLabel(self.widget)
        self.H1.setText(_fromUtf8(""))
        self.H1.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H1.setScaledContents(True)
        self.H1.setObjectName(_fromUtf8("H1"))
        self.gridLayout.addWidget(self.H1, 8, 1, 1, 1)
        self.label_116 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_116.setFont(font)
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.gridLayout.addWidget(self.label_116, 7, 0, 1, 1)
        self.H3 = QtGui.QLabel(self.widget)
        self.H3.setText(_fromUtf8(""))
        self.H3.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H3.setScaledContents(True)
        self.H3.setObjectName(_fromUtf8("H3"))
        self.gridLayout.addWidget(self.H3, 8, 3, 1, 1)
        self.G9 = QtGui.QLabel(self.widget)
        self.G9.setText(_fromUtf8(""))
        self.G9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G9.setScaledContents(True)
        self.G9.setObjectName(_fromUtf8("G9"))
        self.gridLayout.addWidget(self.G9, 7, 9, 1, 1)
        self.H4 = QtGui.QLabel(self.widget)
        self.H4.setText(_fromUtf8(""))
        self.H4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H4.setScaledContents(True)
        self.H4.setObjectName(_fromUtf8("H4"))
        self.gridLayout.addWidget(self.H4, 8, 4, 1, 1)
        self.H5 = QtGui.QLabel(self.widget)
        self.H5.setText(_fromUtf8(""))
        self.H5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H5.setScaledContents(True)
        self.H5.setObjectName(_fromUtf8("H5"))
        self.gridLayout.addWidget(self.H5, 8, 5, 1, 1)
        self.G7 = QtGui.QLabel(self.widget)
        self.G7.setText(_fromUtf8(""))
        self.G7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G7.setScaledContents(True)
        self.G7.setObjectName(_fromUtf8("G7"))
        self.gridLayout.addWidget(self.G7, 7, 7, 1, 1)
        self.G2 = QtGui.QLabel(self.widget)
        self.G2.setText(_fromUtf8(""))
        self.G2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G2.setScaledContents(True)
        self.G2.setObjectName(_fromUtf8("G2"))
        self.gridLayout.addWidget(self.G2, 7, 2, 1, 1)
        self.G8 = QtGui.QLabel(self.widget)
        self.G8.setText(_fromUtf8(""))
        self.G8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G8.setScaledContents(True)
        self.G8.setObjectName(_fromUtf8("G8"))
        self.gridLayout.addWidget(self.G8, 7, 8, 1, 1)
        self.H6 = QtGui.QLabel(self.widget)
        self.H6.setText(_fromUtf8(""))
        self.H6.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H6.setScaledContents(True)
        self.H6.setObjectName(_fromUtf8("H6"))
        self.gridLayout.addWidget(self.H6, 8, 6, 1, 1)
        self.H8 = QtGui.QLabel(self.widget)
        self.H8.setText(_fromUtf8(""))
        self.H8.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H8.setScaledContents(True)
        self.H8.setObjectName(_fromUtf8("H8"))
        self.gridLayout.addWidget(self.H8, 8, 8, 1, 1)
        self.F9 = QtGui.QLabel(self.widget)
        self.F9.setText(_fromUtf8(""))
        self.F9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.F9.setScaledContents(True)
        self.F9.setObjectName(_fromUtf8("F9"))
        self.gridLayout.addWidget(self.F9, 6, 9, 1, 1)
        self.G4 = QtGui.QLabel(self.widget)
        self.G4.setText(_fromUtf8(""))
        self.G4.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G4.setScaledContents(True)
        self.G4.setObjectName(_fromUtf8("G4"))
        self.gridLayout.addWidget(self.G4, 7, 4, 1, 1)
        self.G5 = QtGui.QLabel(self.widget)
        self.G5.setText(_fromUtf8(""))
        self.G5.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.G5.setScaledContents(True)
        self.G5.setObjectName(_fromUtf8("G5"))
        self.gridLayout.addWidget(self.G5, 7, 5, 1, 1)
        self.H2 = QtGui.QLabel(self.widget)
        self.H2.setText(_fromUtf8(""))
        self.H2.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H2.setScaledContents(True)
        self.H2.setObjectName(_fromUtf8("H2"))
        self.gridLayout.addWidget(self.H2, 8, 2, 1, 1)
        self.H7 = QtGui.QLabel(self.widget)
        self.H7.setText(_fromUtf8(""))
        self.H7.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H7.setScaledContents(True)
        self.H7.setObjectName(_fromUtf8("H7"))
        self.gridLayout.addWidget(self.H7, 8, 7, 1, 1)
        self.H9 = QtGui.QLabel(self.widget)
        self.H9.setText(_fromUtf8(""))
        self.H9.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H9.setScaledContents(True)
        self.H9.setObjectName(_fromUtf8("H9"))
        self.gridLayout.addWidget(self.H9, 8, 9, 1, 1)
        self.H11 = QtGui.QLabel(self.widget)
        self.H11.setText(_fromUtf8(""))
        self.H11.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H11.setScaledContents(True)
        self.H11.setObjectName(_fromUtf8("H11"))
        self.gridLayout.addWidget(self.H11, 8, 11, 1, 1)
        self.H10 = QtGui.QLabel(self.widget)
        self.H10.setText(_fromUtf8(""))
        self.H10.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H10.setScaledContents(True)
        self.H10.setObjectName(_fromUtf8("H10"))
        self.gridLayout.addWidget(self.H10, 8, 10, 1, 1)
        self.H12 = QtGui.QLabel(self.widget)
        self.H12.setText(_fromUtf8(""))
        self.H12.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
        self.H12.setScaledContents(True)
        self.H12.setObjectName(_fromUtf8("H12"))
        self.gridLayout.addWidget(self.H12, 8, 12, 1, 1)
        self.label_97 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_97.setFont(font)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.gridLayout.addWidget(self.label_97, 0, 1, 1, 1)
        self.A1.raise_()
        self.B1.raise_()
        self.C1.raise_()
        self.D1.raise_()
        self.E1.raise_()
        self.F1.raise_()
        self.G1.raise_()
        self.H1.raise_()
        self.F2.raise_()
        self.G2.raise_()
        self.A2.raise_()
        self.D2.raise_()
        self.E2.raise_()
        self.B2.raise_()
        self.H2.raise_()
        self.C2.raise_()
        self.F3.raise_()
        self.G3.raise_()
        self.A3.raise_()
        self.D3.raise_()
        self.E3.raise_()
        self.B3.raise_()
        self.H3.raise_()
        self.C3.raise_()
        self.F4.raise_()
        self.G4.raise_()
        self.A4.raise_()
        self.D4.raise_()
        self.E4.raise_()
        self.B4.raise_()
        self.H4.raise_()
        self.C4.raise_()
        self.F5.raise_()
        self.G5.raise_()
        self.A5.raise_()
        self.D5.raise_()
        self.E5.raise_()
        self.B5.raise_()
        self.H5.raise_()
        self.C5.raise_()
        self.F6.raise_()
        self.G6.raise_()
        self.A6.raise_()
        self.D6.raise_()
        self.E6.raise_()
        self.B6.raise_()
        self.H6.raise_()
        self.C6.raise_()
        self.F7.raise_()
        self.G7.raise_()
        self.A7.raise_()
        self.D7.raise_()
        self.E7.raise_()
        self.B7.raise_()
        self.H7.raise_()
        self.C7.raise_()
        self.F8.raise_()
        self.G8.raise_()
        self.A8.raise_()
        self.D8.raise_()
        self.E8.raise_()
        self.B8.raise_()
        self.H8.raise_()
        self.C8.raise_()
        self.F9.raise_()
        self.G9.raise_()
        self.A9.raise_()
        self.D9.raise_()
        self.E9.raise_()
        self.B9.raise_()
        self.H9.raise_()
        self.C9.raise_()
        self.F10.raise_()
        self.G10.raise_()
        self.A10.raise_()
        self.D10.raise_()
        self.E10.raise_()
        self.B10.raise_()
        self.H10.raise_()
        self.C10.raise_()
        self.F11.raise_()
        self.G11.raise_()
        self.A11.raise_()
        self.D11.raise_()
        self.E11.raise_()
        self.B11.raise_()
        self.H11.raise_()
        self.C11.raise_()
        self.E12.raise_()
        self.B12.raise_()
        self.C12.raise_()
        self.D12.raise_()
        self.A12.raise_()
        self.G12.raise_()
        self.F12.raise_()
        self.H12.raise_()
        self.label_97.raise_()
        self.label_98.raise_()
        self.label_99.raise_()
        self.label_100.raise_()
        self.label_101.raise_()
        self.label_102.raise_()
        self.label_103.raise_()
        self.label_104.raise_()
        self.label_105.raise_()
        self.label_106.raise_()
        self.label_107.raise_()
        self.label_108.raise_()
        self.label_109.raise_()
        self.label_110.raise_()
        self.label_111.raise_()
        self.label_112.raise_()
        self.label_113.raise_()
        self.label_114.raise_()
        self.label_115.raise_()
        self.label_116.raise_()
        self.label_117.raise_()
        self.label_109.raise_()
        self.nextButton.raise_()
        self.label_118.raise_()
        self.label_119.raise_()
        self.clearButton.raise_()

        self.rows = ['A', 'B', 'C', 'D', 'E', 'F','G', 'H']
        self.cols = range(1,13)
        self.selectionDict = {}
        self.wellNames = []

        for row in self.rows:
            self.selectionDict[row] = []
            for column in self.cols:
                self.wellNames.append(row+str(column))
                self.selectionDict[row].append('OFF')
        print self.wellNames
        print self.selectionDict

        self.rubberband = QtGui.QRubberBand(
            QtGui.QRubberBand.Rectangle, self)

        self.setMouseTracking(True)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def mousePressEvent(self, event):
        self.origin = event.pos()

        for child in self.findChildren(QtGui.QLabel):
            rect_correct = QtCore.QRect(child.pos().x(), child.pos().y(), int(str(child.geometry().width())) - 15, int(str(child.geometry().height())) - 15)
            if rect_correct.contains(self.origin):
                if str(child.objectName()) in self.wellNames:
                    name = str(child.objectName())
                    row = name[0]
                    column = int(name[1:len(name)]) - 1
                    if self.selectionDict[row][column] == 'OFF':
                        child.setPixmap(QtGui.QPixmap(_fromUtf8("selectedWellLogo.svg")))
                        self.selectionDict[row][column] = 'ON'
                    elif self.selectionDict[row][column] == 'ON':
                        child.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
                        self.selectionDict[row][column] = 'OFF'
        self.rubberband.setGeometry(
            QtCore.QRect(self.origin, QtCore.QSize()))
        self.rubberband.show()
        QtGui.QWidget.mousePressEvent(self, event)

    def mouseMoveEvent(self, event):
        if self.rubberband.isVisible():
            self.rubberband.setGeometry(
                QtCore.QRect(self.origin, event.pos()).normalized())
        QtGui.QWidget.mouseMoveEvent(self, event)

    def mouseReleaseEvent(self, event):
        if self.rubberband.isVisible():
            self.rubberband.hide()
            #selected = []
            rect = self.rubberband.geometry()
            rect_correct = QtCore.QRect(rect.x(),rect.y(),int(str(rect.width()))-18,int(str(rect.height()))-18)
            for child in self.findChildren(QtGui.QLabel):
                if rect_correct.intersects(child.geometry()):
                    if str(child.objectName()) in self.wellNames:
                        name = str(child.objectName())
                        row = name[0]
                        column = int(name[1:len(name)])-1
                        if self.selectionDict[row][column] == 'OFF':
                            child.setPixmap(QtGui.QPixmap(_fromUtf8("selectedWellLogo.svg")))
                            self.selectionDict[row][column] = 'ON'
                        elif self.selectionDict[row][column] == 'ON':
                            child.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
                            self.selectionDict[row][column] = 'OFF'

        QtGui.QWidget.mouseReleaseEvent(self, event)

    def clearWells(self):
        for child in self.findChildren(QtGui.QLabel):
            if str(child.objectName()) in self.wellNames:
                name = str(child.objectName())
                row = name[0]
                column = int(name[1:len(name)]) - 1
                child.setPixmap(QtGui.QPixmap(_fromUtf8("notSelectedWellLogo.svg")))
                self.selectionDict[row][column] = 'OFF'

    def retranslateUi(self):
        self.setWindowTitle('KAM-Spec 2017')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('KAM-Spec Logo LtoH.svg'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        #self.setWindowTitle(_translate("self", "self", None))
        self.nextButton.setText(_translate("self", "NEXT", None))
        self.label_118.setText(_translate("self", "Click & Drag ", None))
        self.label_119.setText(_translate("self", "to select wells", None))
        self.clearButton.setText(_translate("self", "Clear All", None))
        self.label_107.setText(_translate("self", "11", None))
        self.label_110.setText(_translate("self", "A", None))
        self.label_98.setText(_translate("self", "2", None))
        self.label_99.setText(_translate("self", "3", None))
        self.label_100.setText(_translate("self", "4", None))
        self.label_103.setText(_translate("self", "7", None))
        self.label_106.setText(_translate("self", "10", None))
        self.label_101.setText(_translate("self", "5", None))
        self.label_108.setText(_translate("self", "12", None))
        self.label_105.setText(_translate("self", "9", None))
        self.label_102.setText(_translate("self", "6", None))
        self.label_104.setText(_translate("self", "8", None))
        self.label_111.setText(_translate("self", "B", None))
        self.label_112.setText(_translate("self", "C", None))
        self.label_113.setText(_translate("self", "D", None))
        self.label_115.setText(_translate("self", "F", None))
        self.label_114.setText(_translate("self", "E", None))
        self.label_117.setText(_translate("self", "H", None))
        self.label_116.setText(_translate("self", "G", None))
        self.label_97.setText(_translate("self", "1", None))

def main():
    import sys
    app = QtGui.QApplication(sys.argv)
    app.setStyle("Plastique")
    ex = wellSelectScreen()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()